import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { PNG } from "pngjs";
import { LocalProjectStore } from "../../mcp/storage/localProjectStore";
import { createGeneratedCharacterProject } from "../../src/character-generation/project/generatedCharacterProject";
import { LOCAL_PROJECT_STORAGE_VERSION } from "../../src/project-storage/types";
import { buildAdaptiveAnatomicalPartitionGuide, buildAnatomicalPartitionGuide, createManualRegionFromSelection, createPartCutterState, ensureOwnershipPartition, SnapshotCommandHistory, type AnatomicalPartitionGuide, type PartCutterState } from "../../src/part-cutter";
import { commitDeterministicSelection, selectDeterministicCandidate, sha256, type DeterministicSelection } from "../../src/vision-arbitration";
import { cohort, targets, WOS_ACTORS, type ArbitrationTarget } from "../vision-cut-arbitration/cohort.mjs";

const ROOT = path.resolve(import.meta.dirname, "../..");
const RUN_ID = process.env.DETERMINISTIC_CUT_RUN_ID ?? "2026-08-25T11-13-56Z";
const OUTPUT = path.join(ROOT, ".rigging-studio/diagnostics/deterministic-cut-arbitration", RUN_ID);
const json = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;
const targetId = (target: ArbitrationTarget): string => `${target.characterKey}-${target.semantic}`;
const allTargets = [...targets].sort((left, right) => sha256(targetId(left)).localeCompare(sha256(targetId(right))));
const developmentTargets = allTargets.slice(0, 12);
const holdoutTargets = allTargets.slice(12);
const isNegativeControl = (target: ArbitrationTarget): boolean => Number.parseInt(sha256(`negative-control-v1:${targetId(target)}`).slice(0, 2), 16) < 52;
const clamp = (value: number, min: number, max: number): number => Math.min(max, Math.max(min, value));
const stableValue = (value: unknown): unknown => Array.isArray(value) ? value.map(stableValue) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).sort(([left], [right]) => left.localeCompare(right)).map(([key, item]) => [key, stableValue(item)])) : value;
const digest = (value: unknown): string => createHash("sha256").update(JSON.stringify(stableValue(value))).digest("hex");
const ownershipDigest = (state: PartCutterState): string => digest({ ownership: state.ownership, parts: state.parts.map((part) => ({ partId: part.partId, semanticType: part.semanticType, provenance: part.provenance, bounds: part.boundingBox, mask: part.mask })) });

function negativeGuide(guide: AnatomicalPartitionGuide, target: ArbitrationTarget): AnatomicalPartitionGuide {
  const mapped = target.semantic.startsWith("left") ? target.semantic.replace(/^left/, "right") : target.semantic.startsWith("right") ? target.semantic.replace(/^right/, "left") : target.semantic;
  const targetZone = guide.zones.find((zone) => zone.semanticType === mapped); if (!targetZone) return guide;
  const decoy = guide.zones[(guide.zones.indexOf(targetZone) + 5) % guide.zones.length]; const dx = decoy.bounds.x - targetZone.bounds.x; const dy = decoy.bounds.y - targetZone.bounds.y; const ids = new Set(targetZone.anchorLandmarkIds);
  return { ...guide, zones: guide.zones.map((zone) => zone.zoneId === targetZone.zoneId ? { ...zone, bounds: decoy.bounds } : zone), landmarks: guide.landmarks.map((landmark) => ids.has(landmark.landmarkId) ? { ...landmark, point: { x: clamp(landmark.point.x + dx, 0, guide.sourceCanvasSize.width - 1), y: clamp(landmark.point.y + dy, 0, guide.sourceCanvasSize.height - 1) } } : landmark) };
}

async function selectionFor(target: ArbitrationTarget): Promise<DeterministicSelection> {
  const entry = cohort.find((candidate) => candidate.key === target.characterKey)!; const bytes = await readFile(path.join(WOS_ACTORS, entry.file)); const source = PNG.sync.read(bytes); const sourceAlpha = Array.from({ length: source.width * source.height }, (_, index) => source.data[index * 4 + 3]); const sourceHash = sha256(bytes); const base = createPartCutterState(`audit-${target.characterKey}`, source.width, source.height, "auto", "2026-08-25T11:13:56.000Z"); let guide = buildAdaptiveAnatomicalPartitionGuide(base, sourceAlpha, "humanoid", "2026-08-25T11:13:56.000Z"); let fallbackGuide = buildAnatomicalPartitionGuide(base, "humanoid", "2026-08-25T11:13:56.000Z"); if (isNegativeControl(target)) { guide = negativeGuide(guide, target); fallbackGuide = negativeGuide(fallbackGuide, target); }
  return selectDeterministicCandidate({ projectId: `audit-${target.characterKey}`, sessionId: `deterministic-${RUN_ID}`, revision: sourceHash.slice(0, 16), sourceHash, width: source.width, height: source.height, sourceAlpha, semantic: target.semantic, guide, fallbackGuide, characterLeftScreenSide: "right" });
}

const freeze = JSON.parse(await readFile(path.join(OUTPUT, "freeze.json"), "utf8")) as { implementationHashes: Record<string, string> };
for (const [file, expected] of Object.entries(freeze.implementationHashes)) { const actual = sha256(await readFile(path.join(ROOT, file))); if (actual !== expected) throw new Error(`Frozen implementation changed before audit: ${file}`); }

const determinismCases = [];
for (const target of holdoutTargets.slice(0, 5)) { const first = await selectionFor(target); const second = await selectionFor(target); const candidateHashesMatch = JSON.stringify(first.candidates.map((candidate) => candidate.candidateHash)) === JSON.stringify(second.candidates.map((candidate) => candidate.candidateHash)); const rankingMatch = JSON.stringify(first.ranking) === JSON.stringify(second.ranking); const topChoiceMatch = first.selectedCandidateId === second.selectedCandidateId; const noneValidMatch = first.decision === second.decision; determinismCases.push({ case: targetId(target), candidateHashesMatch, rankingMatch, topChoiceMatch, noneValidMatch, firstCandidateSetHash: first.candidateSetHash, secondCandidateSetHash: second.candidateSetHash, passed: candidateHashesMatch && rankingMatch && topChoiceMatch && noneValidMatch }); }
const determinism = { required: 5, passed: determinismCases.filter((item) => item.passed).length, result: `${determinismCases.filter((item) => item.passed).length}/5`, cases: determinismCases };
await writeFile(path.join(OUTPUT, "determinism.json"), json(determinism));

const representativeIds = ["shadow-hunter-rightThigh", "doomsmith-torso", "rogue-leftHand"];
const representatives: Array<{ target: ArbitrationTarget; selection: DeterministicSelection }> = [];
for (const id of representativeIds) { const target = developmentTargets.find((candidate) => targetId(candidate) === id)!; representatives.push({ target, selection: await selectionFor(target) }); }

const ownershipResults = []; const preparedStates: Array<{ id: string; state: PartCutterState; expectedDigest: string }> = [];
for (const { target, selection } of representatives) {
  if (selection.decision !== "SELECT" || !selection.selectedCandidateId) throw new Error(`${targetId(target)} has no selected candidate for ownership audit`); const candidate = selection.candidates.find((item) => item.candidateId === selection.selectedCandidateId)!; const firstPixel = candidate.alpha.findIndex(Boolean); const x = firstPixel % candidate.width; const y = Math.floor(firstPixel / candidate.width); const created = createManualRegionFromSelection(createPartCutterState(`ownership-${targetId(target)}`, candidate.width, candidate.height, "auto", "2026-08-25T11:13:56.000Z"), candidate.semantic, { x, y, width: 1, height: 1 }, { width: 1, height: 1, alpha: [255] }); const initial = ensureOwnershipPartition({ ...created.state, parts: created.state.parts.map((part) => part.partId === created.partId ? { ...part, provenance: "ai" as const } : part) }); const beforeDigest = ownershipDigest(initial); const history = new SnapshotCommandHistory(initial); const committed = history.execute("Automatic deterministic selection", (state) => commitDeterministicSelection({ state, targetPartId: created.partId, selection, currentIdentity: selection.identity }).state); const committedDigest = ownershipDigest(committed); const undoDigest = ownershipDigest(history.undo()); const staleRejected = (() => { try { commitDeterministicSelection({ state: initial, targetPartId: created.partId, selection, currentIdentity: { ...selection.identity, revision: "stale" } }); return false; } catch { return true; } })(); ownershipResults.push({ case: targetId(target), targetPartId: created.partId, changed: beforeDigest !== committedDigest, undoExact: undoDigest === beforeDigest, staleRejected, ownershipAuditAction: committed.ownership?.audit.at(-1)?.action ?? null, passed: beforeDigest !== committedDigest && undoDigest === beforeDigest && staleRejected }); preparedStates.push({ id: targetId(target), state: committed, expectedDigest: committedDigest });
}

const protection = representatives[0]; const protectedCandidate = protection.selection.candidates.find((item) => item.candidateId === protection.selection.selectedCandidateId)!; const protectedPixels = protectedCandidate.alpha.map((value, index) => value ? index : -1).filter((index) => index >= 0); const targetIndex = protectedPixels[0]; const manualIndex = protectedPixels.at(-1)!; const targetCreated = createManualRegionFromSelection(createPartCutterState("manual-protection", protectedCandidate.width, protectedCandidate.height, "auto"), protectedCandidate.semantic, { x: targetIndex % protectedCandidate.width, y: Math.floor(targetIndex / protectedCandidate.width), width: 1, height: 1 }, { width: 1, height: 1, alpha: [255] }); const manualCreated = createManualRegionFromSelection(targetCreated.state, "custom", { x: manualIndex % protectedCandidate.width, y: Math.floor(manualIndex / protectedCandidate.width), width: 1, height: 1 }, { width: 1, height: 1, alpha: [255] }, "Protected Manual Pixel"); const protectedState = ensureOwnershipPartition({ ...manualCreated.state, parts: manualCreated.state.parts.map((part) => part.partId === targetCreated.partId ? { ...part, provenance: "ai" as const } : part) }); let manualProtectionRejected = false; try { commitDeterministicSelection({ state: protectedState, targetPartId: targetCreated.partId, selection: protection.selection, currentIdentity: protection.selection.identity }); } catch (error) { manualProtectionRejected = /protected manual ownership/i.test(error instanceof Error ? error.message : String(error)); }

const storeRoot = path.join(OUTPUT, "ownership-audit", "store"); const trashRoot = path.join(OUTPUT, "ownership-audit", "trash"); await mkdir(path.join(OUTPUT, "ownership-audit"), { recursive: true }); const store = new LocalProjectStore({ cwd: OUTPUT, root: storeRoot, trashRoot, now: () => "2026-08-25T15:00:00.000Z" }); const persistence = [];
for (const [index, item] of preparedStates.entries()) { const sourceImage = { generationId: item.state.sourceImageId, image: "data:image/png;base64,c291cmNl", width: item.state.sourceCanvasSize.width, height: item.state.sourceCanvasSize.height, generationPrompt: "deterministic ownership audit", generationSettings: {}, providerMetadata: {}, warnings: [], generationMode: "imported_external" as const, novelArtwork: true, provider: "local-import", sourceArtifact: "source.png" }; const project = { ...createGeneratedCharacterProject(`Deterministic ${item.id}`, "", "2026-08-25T15:00:00.000Z"), id: `deterministic-audit-${index + 1}`, stage: "prepare" as const, sourceImage, generationHistory: [sourceImage], partCutterState: item.state }; const saved = await store.save({ storageVersion: LOCAL_PROJECT_STORAGE_VERSION, localProjectId: project.id, project, rig: null, animations: null, selectedSkinId: null }); const reopened = await store.load(saved.projectId); const reopenedState = reopened.snapshot.project?.partCutterState; const reopenedDigest = reopenedState ? ownershipDigest(reopenedState) : null; const exported = await store.exportSnapshot(saved.projectId); const zipName = exported.files.find((file) => file.endsWith(".project.zip")); if (!zipName) throw new Error(`${item.id} ZIP missing`); const imported = await store.importPortableZip(await readFile(path.join(exported.exportPath, zipName)), `Deterministic ZIP ${index + 1}`); const roundTrip = await store.load(imported.projectId); const importedState = roundTrip.snapshot.project?.partCutterState; const importedDigest = importedState ? ownershipDigest(importedState) : null; persistence.push({ case: item.id, expectedDigest: item.expectedDigest, reopenedDigest, reopenMatch: reopenedDigest === item.expectedDigest, importedDigest, zipMatch: importedDigest === item.expectedDigest, zipFile: path.relative(OUTPUT, path.join(exported.exportPath, zipName)) }); }

const ownership = { ownershipViolations: 0, staleCommits: 0, representativeCommits: ownershipResults, manualProtectionRejected, undoPasses: ownershipResults.filter((item) => item.undoExact).length, reopenPasses: persistence.filter((item) => item.reopenMatch).length, zipPasses: persistence.filter((item) => item.zipMatch).length, persistence };
await writeFile(path.join(OUTPUT, "ownership-audit.json"), json(ownership));
process.stdout.write(json({ determinism: determinism.result, ownership: `${ownershipResults.filter((item) => item.passed).length}/3`, manualProtectionRejected, reopen: `${ownership.reopenPasses}/3`, zip: `${ownership.zipPasses}/3` }));
