import { describe, expect, it } from "vitest";
import { createGeneratedCharacterProject, parseGeneratedCharacterProject, serializeGeneratedCharacterProject } from "../../src/character-generation/project/generatedCharacterProject";
import { analyzeSilhouette, buildAdaptiveAnatomicalPartitionGuide, buildAnatomicalPartitionGuide, createPartCutterState, moveAdaptiveLandmark, partCutterStateSchema } from "../../src/part-cutter";

const WIDTH = 128; const HEIGHT = 128;
const blank = () => new Array<number>(WIDTH * HEIGHT).fill(0);
const rect = (alpha: number[], x: number, y: number, width: number, height: number) => { for (let py = Math.max(0, y); py < Math.min(HEIGHT, y + height); py += 1) for (let px = Math.max(0, x); px < Math.min(WIDTH, x + width); px += 1) alpha[py * WIDTH + px] = 255; };
const ellipse = (alpha: number[], cx: number, cy: number, rx: number, ry: number) => { for (let y = Math.max(0, cy - ry); y <= Math.min(HEIGHT - 1, cy + ry); y += 1) for (let x = Math.max(0, cx - rx); x <= Math.min(WIDTH - 1, cx + rx); x += 1) if (((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2 <= 1) alpha[y * WIDTH + x] = 255; };
const line = (alpha: number[], ax: number, ay: number, bx: number, by: number, radius: number) => { const length = Math.max(1, Math.ceil(Math.hypot(bx - ax, by - ay))); for (let step = 0; step <= length; step += 1) ellipse(alpha, Math.round(ax + (bx - ax) * step / length), Math.round(ay + (by - ay) * step / length), radius, radius); };
type Shape = "standard" | "broad" | "narrow" | "armor" | "robe" | "extreme";
const sprite = (shape: Shape) => { const alpha = blank(); const extreme = shape === "extreme"; const broad = shape === "broad"; const narrow = shape === "narrow"; const armor = shape === "armor"; const robe = shape === "robe"; ellipse(alpha, 64, extreme ? 34 : 28, extreme ? 29 : broad ? 24 : 22, extreme ? 27 : 22); rect(alpha, broad ? 38 : narrow ? 55 : 48, extreme ? 58 : 50, broad ? 52 : narrow ? 18 : 32, extreme ? 23 : 33); if (armor) { rect(alpha, 27, 49, 74, 14); rect(alpha, 45, 50, 38, 35); } line(alpha, broad ? 41 : 49, 57, broad ? 22 : 33, 83, broad ? 7 : narrow ? 3 : 5); line(alpha, broad ? 87 : 79, 57, broad ? 106 : 95, 83, broad ? 7 : narrow ? 3 : 5); if (robe) { for (let y = 75; y < 115; y += 1) rect(alpha, Math.round(45 - (y - 75) * .25), y, Math.round(38 + (y - 75) * .5), 1); rect(alpha, 38, 111, 18, 8); rect(alpha, 72, 111, 18, 8); } else { line(alpha, 55, extreme ? 80 : 80, 50, 112, broad ? 8 : narrow ? 3 : 5); line(alpha, 73, extreme ? 80 : 80, 78, 112, broad ? 8 : narrow ? 3 : 5); ellipse(alpha, 46, 115, broad ? 11 : 8, 5); ellipse(alpha, 82, 115, broad ? 11 : 8, 5); } return alpha; };
const guide = (shape: Shape = "standard", profile: "humanoid" | "digitigrade" | "custom" = "humanoid") => buildAdaptiveAnatomicalPartitionGuide(createPartCutterState(`fixture-${shape}`, WIDTH, HEIGHT), sprite(shape), profile, "2026-08-22T10:00:00.000Z");
const point = (result: ReturnType<typeof guide>, id: string) => result.landmarks.find((landmark) => landmark.landmarkId === id)!.point;
const fullZonePixels = (result: ReturnType<typeof guide>) => result.zones.flatMap((zone) => zone.mask!.alpha.map((value, index) => value ? `${zone.bounds.x + index % zone.mask!.width},${zone.bounds.y + Math.floor(index / zone.mask!.width)}` : null).filter((value): value is string => Boolean(value)));

describe("proportion-adaptive anatomical guide", () => {
  it("builds a source-alpha silhouette profile without transparent padding", () => { const alpha = sprite("standard"); const profile = analyzeSilhouette(alpha, WIDTH, HEIGHT); expect(profile.foregroundBounds.x).toBeGreaterThan(0); expect(profile.foregroundBounds.y).toBeGreaterThan(0); expect(profile.bottommostForeground).toBeLessThan(HEIGHT - 1); expect(profile.rows).toHaveLength(HEIGHT); expect(profile.columns).toHaveLength(WIDTH); expect(profile.foregroundPixelCount).toBeGreaterThan(1000); });
  it("accepts an oversized chibi head and measures its reusable proportions", () => { const result = guide("extreme", "custom"); const descriptor = result.adaptiveMetadata!.proportionDescriptor; expect(descriptor.headHeightRatio).toBeGreaterThan(.35); expect(["large_head_extreme", "tall_chibi"]).toContain(descriptor.archetype); expect(point(result, "head").y).toBeLessThan(point(result, "neck").y); });
  it("keeps short chibi limb chains structurally ordered", () => { const result = guide("extreme", "custom"); expect(point(result, "leftShoulder").y).toBeLessThan(point(result, "leftElbow").y); expect(point(result, "leftElbow").y).toBeLessThan(point(result, "leftWrist").y); expect(point(result, "leftHip").y).toBeLessThan(point(result, "leftKnee").y); expect(point(result, "leftKnee").y).toBeLessThan(point(result, "leftAnkle").y); });
  it("classifies a broad dwarf silhouette without realistic-proportion rejection", () => { const result = guide("broad", "custom"); expect(result.adaptiveMetadata!.proportionDescriptor.archetype).toBe("broad_chibi"); expect(point(result, "rightShoulder").x - point(result, "leftShoulder").x).toBeGreaterThan(35); expect(result.zones.find((zone) => zone.semanticType === "leftUpperArm")!.mask!.alpha.some(Boolean)).toBe(true); });
  it("adapts corridor width for narrow and broad limbs", () => { const narrow = guide("narrow"); const broad = guide("broad", "custom"); const pixels = (result: ReturnType<typeof guide>) => result.zones.find((zone) => zone.semanticType === "leftUpperArm")!.mask!.alpha.filter(Boolean).length; expect(pixels(broad)).toBeGreaterThan(pixels(narrow)); });
  it("keeps armored shoulder joints inside the outer armor silhouette", () => { const result = guide("armor"); const bounds = result.adaptiveMetadata!.proportionDescriptor.foregroundBounds; expect(point(result, "leftShoulder").x - bounds.x).toBeGreaterThan(10); expect(bounds.x + bounds.width - point(result, "rightShoulder").x).toBeGreaterThan(10); expect(result.landmarks.find((item) => item.landmarkId === "leftShoulder")!.method).toContain("armor"); });
  it("records centerline evidence for visible bent-arm landmarks", () => { const result = guide(); expect(result.landmarks.find((item) => item.landmarkId === "leftElbow")).toMatchObject({ source: "centerline", visibility: "visible" }); expect(result.landmarks.find((item) => item.landmarkId === "leftWrist")!.method).toContain("distal branch"); });
  it("marks concealed robe landmarks as inferred rather than visible truth", () => { const result = guide("robe"); expect(result.adaptiveMetadata!.inferredLandmarkIds).toContain("leftKnee"); expect(result.landmarks.find((item) => item.landmarkId === "rightAnkle")).toMatchObject({ source: "inferred_hidden", visibility: "inferred" }); });
  it("routes digitigrade profiles through an explicit hock topology", () => { const result = guide("standard", "digitigrade"); expect(result.adaptiveMetadata).toMatchObject({ topology: "digitigrade", topologyNeedsReview: false }); expect(point(result, "leftHock")).toBeDefined(); expect(point(result, "rightHock")).toBeDefined(); });
  it("preserves character-left and character-right chain ordering", () => { const result = guide(); for (const joint of ["Shoulder", "Elbow", "Wrist", "Hip", "Knee", "Ankle"]) expect(point(result, `left${joint}`).x).toBeLessThan(point(result, `right${joint}`).x); });
  it("rebuilds only affected zones after one direct landmark move", () => { const alpha = sprite("standard"); const before = guide(); const rightArm = before.zones.filter((zone) => zone.semanticType.startsWith("right")).map((zone) => JSON.stringify(zone)); const moved = moveAdaptiveLandmark(before, "leftElbow", { x: point(before, "leftElbow").x - 4, y: point(before, "leftElbow").y + 3 }, alpha); expect(moved.landmarks.find((item) => item.landmarkId === "leftElbow")).toMatchObject({ source: "manual", visibility: "manual", confidence: 1 }); expect(moved.zones.find((zone) => zone.semanticType === "leftUpperArm")).not.toEqual(before.zones.find((zone) => zone.semanticType === "leftUpperArm")); expect(moved.zones.filter((zone) => zone.semanticType.startsWith("right")).map((zone) => JSON.stringify(zone))).toEqual(rightArm); });
  it("stores inspectable heuristic confidence and evidence source", () => { const result = guide(); result.landmarks.forEach((landmark) => { expect(landmark.confidence).toBeGreaterThanOrEqual(0); expect(landmark.confidence).toBeLessThanOrEqual(1); expect(landmark.source).toBeTruthy(); expect(landmark.method).toBeTruthy(); }); });
  it("round-trips adaptive metadata, masks, and topology through project persistence", () => { const result = guide("standard", "digitigrade"); const state = { ...createPartCutterState("persist", WIDTH, HEIGHT), anatomicalGuide: result }; const project = { ...createGeneratedCharacterProject("Adaptive", ""), partCutterState: state }; const parsed = parseGeneratedCharacterProject(JSON.parse(serializeGeneratedCharacterProject(project)) as unknown); expect(parsed.success).toBe(true); if (parsed.success) expect(parsed.data.partCutterState?.anatomicalGuide).toEqual(result); });
  it("loads legacy fixed guides without silently adding adaptive metadata", () => { const state = createPartCutterState("legacy", WIDTH, HEIGHT); const legacy = { ...state, anatomicalGuide: buildAnatomicalPartitionGuide(state) }; const parsed = partCutterStateSchema.parse(JSON.parse(JSON.stringify(legacy))); expect(parsed.anatomicalGuide?.adaptiveMetadata).toBeUndefined(); expect(parsed.anatomicalGuide?.landmarks.every((landmark) => landmark.source === undefined)).toBe(true); });
  it("keeps geometry finite, bounded, non-empty, and exclusively owned", () => { for (const shape of ["standard", "broad", "narrow", "armor", "robe", "extreme"] as const) { const result = guide(shape, shape === "broad" || shape === "extreme" ? "custom" : "humanoid"); result.landmarks.forEach((landmark) => { expect(Number.isFinite(landmark.point.x) && Number.isFinite(landmark.point.y)).toBe(true); expect(landmark.point.x).toBeGreaterThanOrEqual(0); expect(landmark.point.x).toBeLessThan(WIDTH); expect(landmark.point.y).toBeGreaterThanOrEqual(0); expect(landmark.point.y).toBeLessThan(HEIGHT); }); result.zones.forEach((zone) => { expect(zone.mask?.alpha.some(Boolean)).toBe(true); expect(zone.bounds.x + zone.bounds.width).toBeLessThanOrEqual(WIDTH); expect(zone.bounds.y + zone.bounds.height).toBeLessThanOrEqual(HEIGHT); }); const pixels = fullZonePixels(result); expect(new Set(pixels).size).toBe(pixels.length); } });
  it("initializes interactively on deterministic fixtures", () => { const started = performance.now(); for (let index = 0; index < 8; index += 1) guide(index % 2 ? "extreme" : "standard", index % 2 ? "custom" : "humanoid"); expect(performance.now() - started).toBeLessThan(500); });
});
