import { describe, expect, it } from "vitest";
import { buildAnatomicalPartitionGuide, createPartCutterState } from "../../src/part-cutter";
import { assertCurrentSelectionIdentity, selectDeterministicCandidate, sha256 } from "../../src/vision-arbitration";

const width = 48; const height = 48; const guide = buildAnatomicalPartitionGuide(createPartCutterState("synthetic", width, height), "humanoid", "2026-08-25T11:13:56.000Z");
const select = (sourceAlpha: readonly number[], semantic = "leftForearm" as const) => selectDeterministicCandidate({ projectId: "project", sessionId: "session", revision: "revision", sourceHash: sha256(Uint8Array.from(sourceAlpha)), width, height, sourceAlpha, semantic, guide, characterLeftScreenSide: "right" });
const shape = (predicate: (x: number, y: number) => boolean): number[] => Array.from({ length: width * height }, (_, index) => predicate(index % width, Math.floor(index / width)) ? 255 : 0);

describe("deterministic geometric selection", () => {
  it.each([
    ["diagonal limb", shape((x, y) => y >= 18 && y <= 32 && Math.abs(x - (27 + (y - 18) * .55)) <= 3)],
    ["narrow limb", shape((x, y) => x >= 32 && x <= 35 && y >= 18 && y <= 32)],
    ["thick chibi limb", shape((x, y) => x >= 28 && x <= 39 && y >= 17 && y <= 33)],
    ["fused upper arm torso", shape((x, y) => (x >= 15 && x <= 35 && y >= 12 && y <= 31) || (x >= 30 && x <= 40 && y >= 15 && y <= 31))],
    ["asymmetric limb", shape((x, y) => x >= 30 && x <= 39 && y >= 18 && y <= 30 || x >= 35 && x <= 42 && y >= 25 && y <= 34)],
  ])("generates bounded foreground-only candidates for %s", (_name, source) => { const result = select(source); expect(result.candidates.length).toBeGreaterThanOrEqual(2); expect(result.candidates.length).toBeLessThanOrEqual(5); expect(result.candidates.every((candidate) => candidate.alpha.every((value, index) => !value || source[index]))).toBe(true); });
  it("is deterministic and exposes transparent scoring", () => { const source = shape((x, y) => x >= 29 && x <= 38 && y >= 18 && y <= 32); const first = select(source); const second = select(source); expect(first.candidateSetHash).toBe(second.candidateSetHash); expect(first.selectedCandidateId).toBe(second.selectedCandidateId); expect(first.candidates.map((candidate) => candidate.candidateHash)).toEqual(second.candidates.map((candidate) => candidate.candidateHash)); expect(first.candidates.every((candidate) => Object.keys(candidate.features).length === 14 && Object.keys(candidate.weights).length === 14 && ["adaptive", "canonical"].includes(candidate.topologySource) && Object.keys(candidate.geometryParameters).length > 0)).toBe(true); });
  it("rejects a semantically impossible guide location without a negative-control flag", () => { const source = shape((x, y) => x >= 15 && x <= 34 && y >= 32 && y <= 47); const decoy = { ...guide, zones: guide.zones.map((zone) => zone.semanticType === "head" ? { ...zone, bounds: { x: 15, y: 34, width: 20, height: 12 } } : zone), landmarks: guide.landmarks.map((landmark) => landmark.landmarkId === "neck" ? { ...landmark, point: { x: 24, y: 39 } } : landmark.landmarkId === "head" ? { ...landmark, point: { x: 24, y: 35 } } : landmark) }; const result = selectDeterministicCandidate({ projectId: "project", sessionId: "session", revision: "revision", sourceHash: sha256(Uint8Array.from(source)), width, height, sourceAlpha: source, semantic: "head", guide: decoy, fallbackGuide: decoy }); expect(result.decision).toBe("NONE_VALID"); expect(result.candidates.every((candidate) => candidate.rejectionReasons.includes("ANATOMICALLY_IMPOSSIBLE_LOCATION"))).toBe(true); });
  it("protects manual ownership", () => { const source = shape((x, y) => x >= 25 && x <= 40 && y >= 15 && y <= 35); const protectedAlpha = shape((x, y) => x >= 30 && x <= 34 && y >= 20 && y <= 25); const result = selectDeterministicCandidate({ projectId: "project", sessionId: "session", revision: "revision", sourceHash: sha256(Uint8Array.from(source)), width, height, sourceAlpha: source, protectedAlpha, semantic: "leftForearm", guide, characterLeftScreenSide: "right" }); expect(result.candidates.every((candidate) => candidate.alpha.every((value, index) => !value || !protectedAlpha[index]))).toBe(true); });
  it("rejects a stale commit identity", () => { const source = shape((x, y) => x >= 29 && x <= 38 && y >= 18 && y <= 32); const result = select(source); expect(() => assertCurrentSelectionIdentity(result, { ...result.identity, revision: "changed" })).toThrow(/stale/i); });
  it("covers endpoint feet without unbounded masks", () => { const source = shape((x, y) => x >= 22 && x <= 34 && y >= 35 && y <= 47); const result = select(source, "leftFoot" as never); expect(result.candidates.length).toBeGreaterThanOrEqual(2); expect(Math.max(...result.candidates.map((candidate) => candidate.pixelCount))).toBeLessThan(width * height / 3); });
  it("returns NONE_VALID when the target has no foreground relationship", () => { const source = shape((x, y) => x >= 1 && x <= 5 && y >= 1 && y <= 5); expect(select(source).decision).toBe("NONE_VALID"); });
});
