import { describe, expect, it } from "vitest";
import { CandidateReviewService } from "../../mcp/vision-arbitration";
import { arbitrateCandidates, candidateSetHash, generateCutCandidates, sha256, validateCandidateReviewResult, type CandidateReviewJob, type CandidateReviewProvider, type CandidateReviewResult, type CutCandidate } from "../../src/vision-arbitration";
import type { VisionReviewCapabilities } from "../../src/vision-review";

const width = 12; const height = 12; const source = Array.from({ length: width * height }, (_, index) => { const x = index % width; const y = Math.floor(index / width); return x >= 2 && x <= 9 && y >= 1 && y <= 10 ? 255 : 0; }); const sourceHash = sha256(Uint8Array.from(source));
const generated = () => generateCutCandidates({ jobId: "review-job", projectId: "project-a", sessionId: "session-a", revision: "revision-a", semantic: "leftForearm", width, height, sourceAlpha: source, sourceHash, envelope: { x: 5, y: 3, width: 5, height: 5 }, anchors: [{ x: 7, y: 3 }, { x: 8, y: 7 }], characterLeftScreenSide: "right", createdAt: "2026-08-25T08:00:00.000Z" });
const review = (job: CandidateReviewJob, patch: Partial<CandidateReviewResult> = {}): CandidateReviewResult => ({ schemaVersion: 1, jobId: job.jobId, semantic: job.semantic, decision: "SELECT", rankedCandidateIds: job.candidates.map((candidate) => candidate.candidateId), acceptedCandidateId: job.candidates[0].candidateId, confidence: .92, assessments: job.candidates.map((candidate) => ({ candidateId: candidate.candidateId, reasonCodes: candidate.candidateId === job.candidates[0].candidateId ? ["CORRECT_PART"] : ["TOO_BROAD"], sideAssessment: "CHARACTER_LEFT", articulationUsable: true })), reasonCodes: ["CORRECT_PART"], reviewerProvider: "fixture", model: "fixture", sourceHash: job.sourceHash, candidateSetHash: job.candidateSetHash, notes: "bounded fixture verdict", ...patch });
const identity = (job: CandidateReviewJob) => ({ projectId: job.projectId, sessionId: job.sessionId, revision: job.revision, sourceHash: job.sourceHash, candidateSetHash: job.candidateSetHash });

describe("vision-assisted cut candidate arbitration", () => {
  it("generates 2-5 deterministic foreground-only candidates with stable provenance hashes", () => {
    const first = generated(); const second = generated(); expect(first.candidates.length).toBeGreaterThanOrEqual(2); expect(first.candidates.length).toBeLessThanOrEqual(5); expect(first.job.candidateSetHash).toBe(second.job.candidateSetHash); expect(first.candidates.map((candidate) => candidate.candidateHash)).toEqual(second.candidates.map((candidate) => candidate.candidateHash)); expect(first.candidates.every((candidate) => candidate.alpha.every((value, index) => !value || source[index]))).toBe(true);
    expect(first.job.candidateSetHash).toBe(candidateSetHash(sourceHash, "leftForearm", 1, first.job.candidates));
  });

  it("rejects an unknown or incomplete candidate ranking", () => { const { job } = generated(); const invalid = review(job, { rankedCandidateIds: ["UNKNOWN", ...job.candidates.slice(1).map((candidate) => candidate.candidateId)] }); expect(() => validateCandidateReviewResult(invalid, job)).toThrow(/ranking/i); });
  it("rejects a stale candidate-set hash", () => { const { job } = generated(); expect(() => validateCandidateReviewResult(review(job, { candidateSetHash: "0".repeat(64) }), job)).toThrow(/stale|mismatch/i); });
  it("discards a delayed result from another project or revision", () => { const set = generated(); const decision = arbitrateCandidates({ ...set, review: review(set.job), sourceAlpha: source, currentIdentity: { ...identity(set.job), projectId: "project-b" } }); expect(decision).toMatchObject({ status: "STALE", selectedCandidateId: null, failureClass: "STALE_REVIEW" }); });

  it("lets deterministic validation veto a high-confidence vision choice", () => {
    const set = generated(); const first = set.candidates[0]; const poisoned: CutCandidate = { ...first, alpha: first.alpha.map((value, index) => index === 0 ? 255 : value) }; const candidates = [poisoned, ...set.candidates.slice(1)]; const verdict = review(set.job, { acceptedCandidateId: first.candidateId, rankedCandidateIds: set.job.candidates.map((candidate) => candidate.candidateId), confidence: .99 }); const decision = arbitrateCandidates({ job: set.job, candidates, review: verdict, sourceAlpha: source, currentIdentity: identity(set.job) }); expect(decision.selectedCandidateId).not.toBe(first.candidateId); expect(decision.deterministicFindings).toContainEqual(expect.objectContaining({ candidateId: first.candidateId, code: "OUT_OF_FOREGROUND" }));
  });

  it("supports NONE_OF_THE_ABOVE and stops after round two", () => {
    const first = generated(); const none = review(first.job, { decision: "NONE_OF_THE_ABOVE", acceptedCandidateId: null, reasonCodes: ["NONE_VALID"] }); expect(arbitrateCandidates({ ...first, review: none, sourceAlpha: source, currentIdentity: identity(first.job) }).status).toBe("NEEDS_ALTERNATIVE");
    const second = generateCutCandidates({ jobId: "review-job-2", projectId: "project-a", sessionId: "session-a", revision: "revision-a", semantic: "leftForearm", width, height, sourceAlpha: source, sourceHash, envelope: { x: 5, y: 3, width: 5, height: 5 }, anchors: [{ x: 7, y: 3 }, { x: 8, y: 7 }], round: 2, createdAt: "2026-08-25T08:00:01.000Z" }); const secondNone = review(second.job, { decision: "NONE_OF_THE_ABOVE", acceptedCandidateId: null, reasonCodes: ["NONE_VALID"] }); expect(arbitrateCandidates({ ...second, review: secondNone, sourceAlpha: source, currentIdentity: identity(second.job) }).status).toBe("UNRESOLVED");
  });

  it("does not auto-select below the registered confidence threshold", () => { const set = generated(); const decision = arbitrateCandidates({ ...set, review: review(set.job, { confidence: .64 }), sourceAlpha: source, currentIdentity: identity(set.job) }); expect(decision).toMatchObject({ status: "UNRESOLVED", selectedCandidateId: null, failureClass: "LOW_CONFIDENCE_UNRESOLVED" }); });
  it("auto-selects only a high-confidence ranked survivor", () => { const set = generated(); expect(arbitrateCandidates({ ...set, review: review(set.job), sourceAlpha: source, currentIdentity: identity(set.job) })).toMatchObject({ status: "SELECTED", selectedCandidateId: set.job.candidates[0].candidateId }); });
  it("vetoes a high-confidence choice outside the registered relative geometry tolerance", () => { const set = generated(); const ranking = [...set.candidates].sort((left, right) => left.geometryScore - right.geometryScore); const chosen = ranking[0]; const verdict = review(set.job, { rankedCandidateIds: ranking.map((candidate) => candidate.candidateId), acceptedCandidateId: chosen.candidateId, confidence: .99, assessments: set.candidates.map((candidate) => ({ candidateId: candidate.candidateId, reasonCodes: ["CORRECT_PART"], sideAssessment: "CHARACTER_LEFT", articulationUsable: true })) }); const decision = arbitrateCandidates({ ...set, review: verdict, sourceAlpha: source, currentIdentity: identity(set.job), policy: { maximumGeometryScoreDeficit: .01 } }); expect(decision).toMatchObject({ status: "UNRESOLVED", selectedCandidateId: null, failureClass: "GEOMETRY_OVERRULED_GOOD" }); });
  it("leaves medium-confidence geometry/reviewer disagreement unresolved", () => { const set = generated(); const geometry = [...set.candidates].sort((left, right) => right.geometryScore - left.geometryScore)[0]; const different = set.candidates.find((candidate) => candidate.candidateId !== geometry.candidateId)!; const ranking = [different.candidateId, ...set.candidates.filter((candidate) => candidate.candidateId !== different.candidateId).map((candidate) => candidate.candidateId)]; const assessments = set.candidates.map((candidate) => ({ candidateId: candidate.candidateId, reasonCodes: ["CORRECT_PART" as const], sideAssessment: "CHARACTER_LEFT" as const, articulationUsable: true })); const decision = arbitrateCandidates({ ...set, review: review(set.job, { confidence: .75, rankedCandidateIds: ranking, acceptedCandidateId: different.candidateId, assessments }), sourceAlpha: source, currentIdentity: identity(set.job) }); expect(decision.status).toBe("UNRESOLVED"); });

  it("falls back cleanly when the vision provider is unavailable", async () => {
    const set = generated(); const unavailable: CandidateReviewProvider = { id: "unavailable", capabilities: async (): Promise<VisionReviewCapabilities> => ({ providerId: "unavailable", label: "Unavailable", state: "UNAVAILABLE", available: false, multimodal: false, supportsSourceImage: false, supportsMaskImage: false, supportsRenderedPose: false, supportsAnimationFrames: false, structuredOutput: false, localOnly: true, usesExistingAccountSession: false, supportsIterativeReview: false, supportsRelativeRanking: false, supportedJobTypes: [], transport: "none", version: null, model: null, failureReason: "not installed" }), review: async () => { throw new Error("should not run"); } }; const result = await new CandidateReviewService([unavailable]).review(set.job, {}); expect(result.invocation).toBeNull(); expect(result.attempts).toEqual([expect.objectContaining({ outcome: "unavailable" })]);
  });
});
