import type { Point, Rect, SegmentationMask } from "../character-generation/segmentation/segmentationSchema";
import { SEMANTIC_TAXONOMY, type PartSemanticType } from "./semanticTaxonomy";
import type { AnatomicalLandmark, AnatomicalLandmarkId, AnatomicalPartitionGuide, AnatomicalZone, ChibiProportionDescriptor, LandmarkEvidenceSource, LandmarkVisibilityState, PartCutterState } from "./schema";

export type SilhouetteRow = { readonly y: number; readonly left: number | null; readonly right: number | null; readonly width: number; readonly pixelCount: number; readonly centroidX: number | null; readonly componentCount: number };
export type SilhouetteColumn = { readonly x: number; readonly top: number | null; readonly bottom: number | null; readonly height: number; readonly pixelCount: number; readonly centroidY: number | null };
export type SilhouetteProfile = { readonly width: number; readonly height: number; readonly foregroundBounds: Rect; readonly topmostForeground: number; readonly bottommostForeground: number; readonly centerOfMass: Point; readonly foregroundPixelCount: number; readonly rows: readonly SilhouetteRow[]; readonly columns: readonly SilhouetteColumn[] };

const BODY_TYPES = ["head", "torso", "pelvis", "leftUpperArm", "leftForearm", "leftHand", "rightUpperArm", "rightForearm", "rightHand", "leftThigh", "leftLowerLeg", "leftFoot", "rightThigh", "rightLowerLeg", "rightFoot"] as const satisfies readonly PartSemanticType[];
type BodyType = (typeof BODY_TYPES)[number];
const PARENTS: Readonly<Record<(typeof BODY_TYPES)[number], PartSemanticType | null>> = { head: "torso", torso: "pelvis", pelvis: null, leftUpperArm: "torso", leftForearm: "leftUpperArm", leftHand: "leftForearm", rightUpperArm: "torso", rightForearm: "rightUpperArm", rightHand: "rightForearm", leftThigh: "pelvis", leftLowerLeg: "leftThigh", leftFoot: "leftLowerLeg", rightThigh: "pelvis", rightLowerLeg: "rightThigh", rightFoot: "rightLowerLeg" };
const ANCHORS: Readonly<Record<(typeof BODY_TYPES)[number], readonly AnatomicalLandmarkId[]>> = { head: ["neck", "head"], torso: ["pelvis", "chest", "neck"], pelvis: ["pelvis", "leftHip", "rightHip"], leftUpperArm: ["leftShoulder", "leftElbow"], leftForearm: ["leftElbow", "leftWrist"], leftHand: ["leftWrist"], rightUpperArm: ["rightShoulder", "rightElbow"], rightForearm: ["rightElbow", "rightWrist"], rightHand: ["rightWrist"], leftThigh: ["leftHip", "leftKnee"], leftLowerLeg: ["leftKnee", "leftAnkle"], leftFoot: ["leftAnkle"], rightThigh: ["rightHip", "rightKnee"], rightLowerLeg: ["rightKnee", "rightAnkle"], rightFoot: ["rightAnkle"] };
const PARENT_LANDMARKS: Readonly<Record<AnatomicalLandmarkId, AnatomicalLandmarkId | null>> = { root: null, pelvis: "root", chest: "pelvis", neck: "chest", head: "neck", leftShoulder: "chest", leftElbow: "leftShoulder", leftWrist: "leftElbow", rightShoulder: "chest", rightElbow: "rightShoulder", rightWrist: "rightElbow", leftHip: "pelvis", leftKnee: "leftHip", leftAnkle: "leftKnee", rightHip: "pelvis", rightKnee: "rightHip", rightAnkle: "rightKnee", leftHock: "leftKnee", rightHock: "rightKnee" };
const clamp = (value: number, min: number, max: number): number => Math.min(max, Math.max(min, value));
const roundPoint = (point: Point, width: number, height: number): Point => ({ x: clamp(Math.round(point.x), 0, width - 1), y: clamp(Math.round(point.y), 0, height - 1) });
const alphaAt = (alpha: readonly number[], width: number, height: number, x: number, y: number): boolean => x >= 0 && y >= 0 && x < width && y < height && (alpha[Math.round(y) * width + Math.round(x)] ?? 0) > 0;
const elapsed = (start: number): number => Math.max(0, (typeof performance !== "undefined" ? performance.now() : Date.now()) - start);

export function analyzeSilhouette(alpha: readonly number[], width: number, height: number): SilhouetteProfile {
  if (alpha.length !== width * height) throw new Error("Foreground alpha length must equal width × height");
  let minX = width; let minY = height; let maxX = -1; let maxY = -1; let count = 0; let sumX = 0; let sumY = 0;
  const rows: SilhouetteRow[] = [];
  for (let y = 0; y < height; y += 1) {
    let left = width; let right = -1; let rowCount = 0; let rowSum = 0; let components = 0; let active = false;
    for (let x = 0; x < width; x += 1) {
      const foreground = (alpha[y * width + x] ?? 0) > 0;
      if (!foreground) { active = false; continue; }
      if (!active) components += 1; active = true; left = Math.min(left, x); right = Math.max(right, x); rowCount += 1; rowSum += x; count += 1; sumX += x; sumY += y; minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y);
    }
    rows.push({ y, left: right >= 0 ? left : null, right: right >= 0 ? right : null, width: right >= 0 ? right - left + 1 : 0, pixelCount: rowCount, centroidX: rowCount ? rowSum / rowCount : null, componentCount: components });
  }
  if (!count) throw new Error("Adaptive guide requires a non-empty foreground silhouette");
  const columns: SilhouetteColumn[] = [];
  for (let x = 0; x < width; x += 1) { let top = height; let bottom = -1; let columnCount = 0; let columnSum = 0; for (let y = 0; y < height; y += 1) if ((alpha[y * width + x] ?? 0) > 0) { top = Math.min(top, y); bottom = Math.max(bottom, y); columnCount += 1; columnSum += y; } columns.push({ x, top: bottom >= 0 ? top : null, bottom: bottom >= 0 ? bottom : null, height: bottom >= 0 ? bottom - top + 1 : 0, pixelCount: columnCount, centroidY: columnCount ? columnSum / columnCount : null }); }
  return { width, height, foregroundBounds: { x: minX, y: minY, width: maxX - minX + 1, height: maxY - minY + 1 }, topmostForeground: minY, bottommostForeground: maxY, centerOfMass: { x: sumX / count, y: sumY / count }, foregroundPixelCount: count, rows, columns };
}

const smoothRowWidth = (profile: SilhouetteProfile, y: number, radius = 3): number => { let sum = 0; let samples = 0; for (let row = Math.max(0, y - radius); row <= Math.min(profile.height - 1, y + radius); row += 1) { if (profile.rows[row].pixelCount) { sum += profile.rows[row].pixelCount; samples += 1; } } return samples ? sum / samples : 0; };
const rowCentroidOnSide = (alpha: readonly number[], profile: SilhouetteProfile, y: number, side: "left" | "right", centerX: number, fallback: number): number => {
  const { width, height, foregroundBounds: bounds } = profile; const band = Math.max(3, Math.round(bounds.height * .025)); const columns = new Array<number>(width).fill(0);
  for (let row = Math.max(bounds.y, Math.round(y - band)); row <= Math.min(height - 1, Math.round(y + band)); row += 1) for (let x = bounds.x; x < bounds.x + bounds.width; x += 1) if (alpha[row * width + x] && (side === "left" ? x < centerX : x > centerX)) columns[x] += 1;
  const segments: { left: number; right: number; weight: number; centroid: number }[] = []; let x = bounds.x;
  while (x < bounds.x + bounds.width) { while (x < bounds.x + bounds.width && columns[x] === 0) x += 1; const left = x; let weight = 0; let weighted = 0; while (x < bounds.x + bounds.width && columns[x] > 0) { weight += columns[x]; weighted += x * columns[x]; x += 1; } if (weight) segments.push({ left, right: x - 1, weight, centroid: weighted / weight }); }
  const candidates = segments.filter((segment) => side === "left" ? segment.centroid <= centerX : segment.centroid >= centerX);
  if (!candidates.length) return fallback;
  return candidates.sort((a, b) => (Math.abs(a.centroid - fallback) - Math.abs(b.centroid - fallback)) || (b.weight - a.weight))[0].centroid;
};
const foregroundBoundsInBand = (alpha: readonly number[], profile: SilhouetteProfile, top: number, bottom: number, centerX: number, maxDistance: number): Rect => {
  let minX = profile.width; let minY = profile.height; let maxX = -1; let maxY = -1;
  for (let y = clamp(Math.floor(top), 0, profile.height - 1); y <= clamp(Math.ceil(bottom), 0, profile.height - 1); y += 1) for (let x = Math.max(0, Math.floor(centerX - maxDistance)); x <= Math.min(profile.width - 1, Math.ceil(centerX + maxDistance)); x += 1) if (alpha[y * profile.width + x]) { minX = Math.min(minX, x); minY = Math.min(minY, y); maxX = Math.max(maxX, x); maxY = Math.max(maxY, y); }
  return maxX >= minX ? { x: minX, y: minY, width: maxX - minX + 1, height: maxY - minY + 1 } : { x: centerX - 1, y: top, width: 2, height: Math.max(1, bottom - top) };
};

function descriptorFor(alpha: readonly number[], profile: SilhouetteProfile, requestedProfile: AnatomicalPartitionGuide["profile"]): { descriptor: ChibiProportionDescriptor; neckY: number; hiddenLegs: boolean; armorLikely: boolean } {
  const bounds = profile.foregroundBounds; const bottom = bounds.y + bounds.height - 1; const bboxCenter = bounds.x + bounds.width / 2; const bodyCenterX = clamp(bboxCenter + (profile.centerOfMass.x - bboxCenter) * .4, bounds.x, bounds.x + bounds.width - 1);
  const compactSource = bounds.height < profile.height * .82; const tall = bounds.height / bounds.width > 1.42; const foregroundCenterYRatio = (profile.centerOfMass.y - bounds.y) / bounds.height;
  const defaultRatio = compactSource ? .52 : tall ? .45 : .42; const searchTop = Math.round(bounds.y + bounds.height * .30); const searchBottom = Math.round(bounds.y + bounds.height * .60);
  let narrowY = Math.round(bounds.y + bounds.height * defaultRatio); let narrowScore = Number.POSITIVE_INFINITY;
  for (let y = searchTop; y <= searchBottom; y += 1) { const width = smoothRowWidth(profile, y); const above = smoothRowWidth(profile, Math.max(bounds.y, y - Math.round(bounds.height * .08))); const below = smoothRowWidth(profile, Math.min(bottom, y + Math.round(bounds.height * .08))); if (!width || !above || !below) continue; const score = width / Math.max(1, (above + below) / 2) + Math.abs(y - (bounds.y + bounds.height * defaultRatio)) / bounds.height * .45; if (score < narrowScore) { narrowScore = score; narrowY = y; } }
  let neckY = clamp(Math.round(narrowY * .45 + (bounds.y + bounds.height * defaultRatio) * .55), bounds.y + bounds.height * .28, bounds.y + bounds.height * .62);
  let headBounds = foregroundBoundsInBand(alpha, profile, bounds.y, neckY, bodyCenterX, Math.max(bounds.width * .36, bounds.height * .25));
  const provisionalHeadWidthRatio = headBounds.width / bounds.width; const extreme = compactSource && provisionalHeadWidthRatio >= .54 && foregroundCenterYRatio < .49;
  if (extreme) { neckY = Math.max(neckY, Math.round(bounds.y + bounds.height * .57)); headBounds = foregroundBoundsInBand(alpha, profile, bounds.y, neckY, bodyCenterX, Math.max(bounds.width * .42, bounds.height * .3)); }
  const headHeightRatio = headBounds.height / bounds.height; const headWidthRatio = headBounds.width / bounds.width;
  const actuallyExtreme = extreme;
  const torsoProbe = smoothRowWidth(profile, Math.round(neckY + (bottom - neckY) * .30)); const headProbe = Math.max(1, smoothRowWidth(profile, Math.round(headBounds.y + headBounds.height * .55))); const broad = !actuallyExtreme && (torsoProbe / headProbe > 1.48 || compactSource);
  const archetype: ChibiProportionDescriptor["archetype"] = requestedProfile === "digitigrade" ? "digitigrade" : actuallyExtreme ? "large_head_extreme" : broad ? "broad_chibi" : tall ? "tall_chibi" : requestedProfile === "custom" ? "custom" : "standard_chibi";
  const resolvedBodyCenterX = requestedProfile === "digitigrade" ? bboxCenter + (profile.centerOfMass.x - bboxCenter) * .8 : archetype === "large_head_extreme" ? bboxCenter - bounds.width * .02 : bboxCenter;
  const pelvisFactor = extreme ? .66 : broad ? .61 : tall ? .54 : .57; const pelvisY = neckY + (bottom - neckY) * pelvisFactor;
  const lowerComponentRows = profile.rows.slice(Math.round(pelvisY), Math.round(bottom - bounds.height * .08)).filter((row) => row.pixelCount); const separatedRows = lowerComponentRows.filter((row) => row.componentCount >= 2).length; const hiddenLegs = archetype === "tall_chibi" || (lowerComponentRows.length > 0 && separatedRows / lowerComponentRows.length < .68);
  const shoulderRowWidth = smoothRowWidth(profile, Math.round(neckY + (pelvisY - neckY) * .12)); const armorLikely = requestedProfile === "humanoid" && bounds.height / bounds.width > 1.1 && shoulderRowWidth > headProbe * 1.42;
  const torsoHeightRatio = (pelvisY - neckY) / bounds.height; const legLengthRatio = (bottom - pelvisY) / bounds.height; const armLengthRatio = Math.min(1, (pelvisY - neckY) * 1.15 / bounds.height); const overallCompactness = clamp(bounds.width / bounds.height, 0, 2);
  return { descriptor: { foregroundBounds: bounds, headBounds, centerOfMass: profile.centerOfMass, bodyCenterX: resolvedBodyCenterX, headHeightRatio, headWidthRatio, torsoHeightRatio, legLengthRatio, armLengthRatio, overallCompactness, archetype }, neckY, hiddenLegs, armorLikely };
}

type LandmarkInput = { id: AnatomicalLandmarkId; point: Point; source: LandmarkEvidenceSource; visibility: LandmarkVisibilityState; confidence: number; method: string };
function inferLandmarks(alpha: readonly number[], profile: SilhouetteProfile, descriptor: ChibiProportionDescriptor, neckYInput: number, requestedProfile: AnatomicalPartitionGuide["profile"], hiddenLegs: boolean, armorLikely: boolean): AnatomicalLandmark[] {
  const bounds = descriptor.foregroundBounds; const bottom = bounds.y + bounds.height - 1; const bboxCenter = bounds.x + bounds.width / 2; const extreme = descriptor.archetype === "large_head_extreme"; const broad = descriptor.archetype === "broad_chibi"; const tall = descriptor.archetype === "tall_chibi"; const digitigrade = requestedProfile === "digitigrade"; const center = digitigrade ? bboxCenter + (profile.centerOfMass.x - bboxCenter) * .8 : extreme ? bboxCenter - bounds.width * .02 : bboxCenter; const pelvisFactor = extreme ? .66 : broad ? .61 : tall ? .54 : .57;
  const neckY = armorLikely ? neckYInput - bounds.height * .07 : neckYInput; const pelvisY = neckY + (bottom - neckY) * pelvisFactor; const chestY = neckY + (pelvisY - neckY) * .34; const shoulderY = neckY + (pelvisY - neckY) * (armorLikely ? .06 : .12); const rootY = Math.min(profile.height * .96, bottom + bounds.height * .15); const ankleY = rootY - bounds.height * .055; const kneeY = pelvisY + (ankleY - pelvisY) * .55;
  const wideBroad = broad && bounds.width / bounds.height > 1.05; const shoulderHalf = broad && !armorLikely ? bounds.width * .20 : armorLikely ? bounds.width * .18 : Math.max(bounds.width * .16, bounds.height * .095); const hipHalf = Math.max(bounds.width * .055, bounds.height * .035);
  const wristY = shoulderY + (pelvisY - shoulderY) * .74; const elbowY = shoulderY + (wristY - shoulderY) * .50; const armReach = bounds.width * (armorLikely ? .16 : extreme ? .24 : wideBroad ? .36 : .34);
  const leftWristEvidence = rowCentroidOnSide(alpha, profile, wristY, "left", center, center - armReach); const rightWristEvidence = rowCentroidOnSide(alpha, profile, wristY, "right", center, center + armReach); const evidenceWeight = armorLikely ? .08 : .15;
  const leftWristX = (center - armReach) * (1 - evidenceWeight) + leftWristEvidence * evidenceWeight; const rightWristX = (center + armReach) * (1 - evidenceWeight) + rightWristEvidence * evidenceWeight;
  const leftElbowFallback = (center - shoulderHalf + leftWristX) / 2; const rightElbowFallback = (center + shoulderHalf + rightWristX) / 2; const leftElbowEvidence = rowCentroidOnSide(alpha, profile, elbowY, "left", center, leftElbowFallback); const rightElbowEvidence = rowCentroidOnSide(alpha, profile, elbowY, "right", center, rightElbowFallback); const leftElbowX = leftElbowFallback * .85 + leftElbowEvidence * .15; const rightElbowX = rightElbowFallback * .85 + rightElbowEvidence * .15;
  const kneeHalf = digitigrade ? bounds.width * .15 : wideBroad ? bounds.width * .13 : extreme ? bounds.width * .06 : bounds.width * .085; const ankleHalf = digitigrade ? bounds.width * .18 : wideBroad ? bounds.width * .15 : extreme ? bounds.width * .08 : bounds.width * .105;
  const leftKneeX = center - kneeHalf; const rightKneeX = center + kneeHalf; const leftAnkleX = center - ankleHalf; const rightAnkleX = center + ankleHalf;
  const visibleHeadCenterX = descriptor.headBounds.x + descriptor.headBounds.width / 2; const headCenter = { x: center * .7 + visibleHeadCenterX * .3, y: descriptor.headBounds.y + descriptor.headBounds.height * .48 };
  const inputs: LandmarkInput[] = [
    { id: "root", point: { x: center, y: rootY }, source: "silhouette", visibility: "visible", confidence: .9, method: "bottom foreground terminal" },
    { id: "pelvis", point: { x: center, y: pelvisY }, source: hiddenLegs ? "inferred_hidden" : "silhouette", visibility: hiddenLegs ? "inferred" : "visible", confidence: hiddenLegs ? .55 : .78, method: "lower central mass and leg divergence" },
    { id: "chest", point: { x: center, y: chestY }, source: "silhouette", visibility: "visible", confidence: .82, method: "central torso mass" },
    { id: "neck", point: { x: center, y: neckY }, source: "silhouette", visibility: armorLikely ? "needs-review" : "visible", confidence: armorLikely ? .61 : .8, method: "upper-mass narrowing" },
    { id: "head", point: headCenter, source: "silhouette", visibility: "visible", confidence: .88, method: "oversized upper foreground mass" },
    { id: "leftShoulder", point: { x: center - shoulderHalf, y: shoulderY }, source: armorLikely ? "symmetry" : "silhouette", visibility: armorLikely ? "needs-review" : "visible", confidence: armorLikely ? .58 : .77, method: armorLikely ? "inner attachment below armor extent" : "upper-body widening" },
    { id: "leftElbow", point: { x: leftElbowX, y: elbowY }, source: "centerline", visibility: "visible", confidence: .7, method: "limb branch centerline bend" },
    { id: "leftWrist", point: { x: leftWristX, y: wristY }, source: "centerline", visibility: "visible", confidence: .72, method: "distal branch narrowing" },
    { id: "rightShoulder", point: { x: center + shoulderHalf, y: shoulderY }, source: armorLikely ? "symmetry" : "silhouette", visibility: armorLikely ? "needs-review" : "visible", confidence: armorLikely ? .58 : .77, method: armorLikely ? "inner attachment below armor extent" : "upper-body widening" },
    { id: "rightElbow", point: { x: rightElbowX, y: elbowY }, source: "centerline", visibility: "visible", confidence: .7, method: "limb branch centerline bend" },
    { id: "rightWrist", point: { x: rightWristX, y: wristY }, source: "centerline", visibility: "visible", confidence: .72, method: "distal branch narrowing" },
    { id: "leftHip", point: { x: center - hipHalf, y: pelvisY + bounds.height * .012 }, source: hiddenLegs ? "inferred_hidden" : "silhouette", visibility: hiddenLegs ? "inferred" : "visible", confidence: hiddenLegs ? .5 : .76, method: "pelvis width and leg origin" },
    { id: "leftKnee", point: { x: leftKneeX, y: kneeY }, source: hiddenLegs ? "inferred_hidden" : "centerline", visibility: hiddenLegs ? "inferred" : "visible", confidence: hiddenLegs ? .42 : .7, method: hiddenLegs ? "symmetric hidden trajectory" : "leg centerline bend" },
    { id: "leftAnkle", point: { x: leftAnkleX, y: ankleY }, source: hiddenLegs ? "inferred_hidden" : "centerline", visibility: hiddenLegs ? "inferred" : "visible", confidence: hiddenLegs ? .48 : .74, method: hiddenLegs ? "foot-aligned hidden trajectory" : "distal leg narrowing" },
    { id: "rightHip", point: { x: center + hipHalf, y: pelvisY + bounds.height * .012 }, source: hiddenLegs ? "inferred_hidden" : "silhouette", visibility: hiddenLegs ? "inferred" : "visible", confidence: hiddenLegs ? .5 : .76, method: "pelvis width and leg origin" },
    { id: "rightKnee", point: { x: rightKneeX, y: kneeY }, source: hiddenLegs ? "inferred_hidden" : "centerline", visibility: hiddenLegs ? "inferred" : "visible", confidence: hiddenLegs ? .42 : .7, method: hiddenLegs ? "symmetric hidden trajectory" : "leg centerline bend" },
    { id: "rightAnkle", point: { x: rightAnkleX, y: ankleY }, source: hiddenLegs ? "inferred_hidden" : "centerline", visibility: hiddenLegs ? "inferred" : "visible", confidence: hiddenLegs ? .48 : .74, method: hiddenLegs ? "foot-aligned hidden trajectory" : "distal leg narrowing" },
  ];
  if (requestedProfile === "digitigrade") { const hockY = kneeY + (ankleY - kneeY) * .55; inputs.push({ id: "leftHock", point: { x: leftKneeX + (leftAnkleX - leftKneeX) * .35, y: hockY }, source: "centerline", visibility: "needs-review", confidence: .62, method: "digitigrade intermediate bend" }, { id: "rightHock", point: { x: rightKneeX + (rightAnkleX - rightKneeX) * .35, y: hockY }, source: "centerline", visibility: "needs-review", confidence: .62, method: "digitigrade intermediate bend" }); }
  return inputs.map((input) => ({ landmarkId: input.id, point: roundPoint(input.point, profile.width, profile.height), parentLandmarkId: PARENT_LANDMARKS[input.id], confidence: input.confidence, source: input.source, visibility: input.visibility, method: input.method }));
}

const distanceToSegment = (point: Point, a: Point, b: Point): number => { const dx = b.x - a.x; const dy = b.y - a.y; const length = dx * dx + dy * dy; if (!length) return Math.hypot(point.x - a.x, point.y - a.y); const t = clamp(((point.x - a.x) * dx + (point.y - a.y) * dy) / length, 0, 1); return Math.hypot(point.x - (a.x + t * dx), point.y - (a.y + t * dy)); };
const pointInPolygon = (point: Point, polygon: readonly Point[]): boolean => { let inside = false; for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) { const a = polygon[i]; const b = polygon[j]; if ((a.y > point.y) !== (b.y > point.y) && point.x < (b.x - a.x) * (point.y - a.y) / ((b.y - a.y) || 1e-9) + a.x) inside = !inside; } return inside; };
const localRadius = (alpha: readonly number[], width: number, height: number, a: Point, b: Point, fallback: number): number => { const dx = b.x - a.x; const dy = b.y - a.y; const length = Math.max(1, Math.hypot(dx, dy)); const nx = -dy / length; const ny = dx / length; const totals: number[] = []; for (const t of [.25, .5, .75]) { const p = { x: a.x + dx * t, y: a.y + dy * t }; let span = 1; for (const direction of [-1, 1]) for (let step = 1; step <= fallback * 2.5; step += 1) { if (!alphaAt(alpha, width, height, p.x + nx * step * direction, p.y + ny * step * direction)) break; span += 1; } totals.push(span / 2); } return clamp(totals.reduce((sum, value) => sum + value, 0) / Math.max(1, totals.length), Math.max(2, fallback * .45), fallback * 1.45); };
const boundsFromFullMask = (full: Uint8Array, width: number, height: number): { bounds: Rect; mask: SegmentationMask } | null => { let minX = width; let minY = height; let maxX = -1; let maxY = -1; for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) if (full[y * width + x]) { minX = Math.min(minX, x); minY = Math.min(minY, y); maxX = Math.max(maxX, x); maxY = Math.max(maxY, y); } if (maxX < minX) return null; const maskWidth = maxX - minX + 1; const maskHeight = maxY - minY + 1; const cropped = new Array<number>(maskWidth * maskHeight).fill(0); for (let y = 0; y < maskHeight; y += 1) for (let x = 0; x < maskWidth; x += 1) cropped[y * maskWidth + x] = full[(minY + y) * width + minX + x] ?? 0; return { bounds: { x: minX, y: minY, width: maskWidth, height: maskHeight }, mask: { width: maskWidth, height: maskHeight, alpha: cropped } }; };

function adaptiveZones(alpha: readonly number[], width: number, height: number, landmarks: readonly AnatomicalLandmark[], descriptor: ChibiProportionDescriptor): AnatomicalZone[] {
  const byId = new Map(landmarks.map((landmark) => [landmark.landmarkId, landmark.point])); const bounds = descriptor.foregroundBounds; const defaultRadius = Math.max(3, Math.min(bounds.width, bounds.height) * .045); const candidates = new Map<BodyType, { full: Uint8Array; centerline: readonly Point[]; polygon: readonly Point[]; kind: "silhouette-region" | "centerline-corridor" | "terminal-mass" }>();
  const corridor = (type: BodyType, aId: AnatomicalLandmarkId, bId: AnatomicalLandmarkId) => { const a = byId.get(aId)!; const b = byId.get(bId)!; const radius = localRadius(alpha, width, height, a, b, defaultRadius); const full = new Uint8Array(width * height); for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) if (alpha[y * width + x] && distanceToSegment({ x, y }, a, b) <= radius) full[y * width + x] = 255; const dx = b.x - a.x; const dy = b.y - a.y; const length = Math.max(1, Math.hypot(dx, dy)); const nx = -dy / length * radius; const ny = dx / length * radius; candidates.set(type, { full, centerline: [a, b], polygon: [{ x: a.x + nx, y: a.y + ny }, { x: b.x + nx, y: b.y + ny }, { x: b.x - nx, y: b.y - ny }, { x: a.x - nx, y: a.y - ny }], kind: "centerline-corridor" }); };
  const region = (type: BodyType, polygon: readonly Point[], centerline: readonly Point[]) => { const full = new Uint8Array(width * height); for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) if (alpha[y * width + x] && pointInPolygon({ x, y }, polygon)) full[y * width + x] = 255; candidates.set(type, { full, polygon, centerline, kind: "silhouette-region" }); };
  const terminal = (type: BodyType, anchorId: AnatomicalLandmarkId, toward: Point, radiusScale: number) => { const anchor = byId.get(anchorId)!; const radius = defaultRadius * radiusScale; const centerPoint = { x: anchor.x + toward.x, y: anchor.y + toward.y }; const full = new Uint8Array(width * height); for (let y = 0; y < height; y += 1) for (let x = 0; x < width; x += 1) if (alpha[y * width + x] && Math.hypot(x - centerPoint.x, y - centerPoint.y) <= radius) full[y * width + x] = 255; const polygon = Array.from({ length: 8 }, (_, index) => ({ x: centerPoint.x + Math.cos(index / 8 * Math.PI * 2) * radius, y: centerPoint.y + Math.sin(index / 8 * Math.PI * 2) * radius })); candidates.set(type, { full, centerline: [anchor, centerPoint], polygon, kind: "terminal-mass" }); };
  const neck = byId.get("neck")!; const pelvis = byId.get("pelvis")!; const leftShoulder = byId.get("leftShoulder")!; const rightShoulder = byId.get("rightShoulder")!; const leftHip = byId.get("leftHip")!; const rightHip = byId.get("rightHip")!;
  region("head", [{ x: descriptor.headBounds.x, y: descriptor.headBounds.y }, { x: descriptor.headBounds.x + descriptor.headBounds.width, y: descriptor.headBounds.y }, { x: descriptor.headBounds.x + descriptor.headBounds.width, y: neck.y + defaultRadius }, { x: descriptor.headBounds.x, y: neck.y + defaultRadius }], [byId.get("head")!, neck]);
  region("torso", [{ x: leftShoulder.x - defaultRadius, y: neck.y }, { x: rightShoulder.x + defaultRadius, y: neck.y }, { x: rightHip.x + defaultRadius, y: pelvis.y }, { x: leftHip.x - defaultRadius, y: pelvis.y }], [neck, byId.get("chest")!, pelvis]);
  region("pelvis", [{ x: leftHip.x - defaultRadius, y: pelvis.y - defaultRadius }, { x: rightHip.x + defaultRadius, y: pelvis.y - defaultRadius }, { x: rightHip.x + defaultRadius * .8, y: pelvis.y + defaultRadius * 1.8 }, { x: leftHip.x - defaultRadius * .8, y: pelvis.y + defaultRadius * 1.8 }], [leftHip, pelvis, rightHip]);
  corridor("leftUpperArm", "leftShoulder", "leftElbow"); corridor("leftForearm", "leftElbow", "leftWrist"); terminal("leftHand", "leftWrist", { x: -defaultRadius * .5, y: defaultRadius * .2 }, 1.35);
  corridor("rightUpperArm", "rightShoulder", "rightElbow"); corridor("rightForearm", "rightElbow", "rightWrist"); terminal("rightHand", "rightWrist", { x: defaultRadius * .5, y: defaultRadius * .2 }, 1.35);
  corridor("leftThigh", "leftHip", "leftKnee"); corridor("leftLowerLeg", "leftKnee", "leftAnkle"); terminal("leftFoot", "leftAnkle", { x: -defaultRadius * .25, y: defaultRadius * .8 }, 1.7);
  corridor("rightThigh", "rightHip", "rightKnee"); corridor("rightLowerLeg", "rightKnee", "rightAnkle"); terminal("rightFoot", "rightAnkle", { x: defaultRadius * .25, y: defaultRadius * .8 }, 1.7);
  const priority: readonly BodyType[] = ["head", "leftHand", "rightHand", "leftFoot", "rightFoot", "leftForearm", "rightForearm", "leftLowerLeg", "rightLowerLeg", "leftUpperArm", "rightUpperArm", "leftThigh", "rightThigh", "pelvis", "torso"]; const claimed = new Uint8Array(width * height); const built = new Map<BodyType, AnatomicalZone>();
  for (const type of priority) { const candidate = candidates.get(type)!; const exclusive = candidate.full.slice(); for (let index = 0; index < exclusive.length; index += 1) if (exclusive[index] && claimed[index]) exclusive[index] = 0; else if (exclusive[index]) claimed[index] = 1; let extracted = boundsFromFullMask(exclusive, width, height); if (!extracted) { const anchor = byId.get(ANCHORS[type][0])!; let nearest = -1; let nearestDistance = Number.POSITIVE_INFINITY; for (let index = 0; index < alpha.length; index += 1) if (alpha[index] && !claimed[index]) { const x = index % width; const y = Math.floor(index / width); const distance = Math.hypot(x - anchor.x, y - anchor.y); if (distance < nearestDistance) { nearest = index; nearestDistance = distance; } } if (nearest >= 0) { const fallback = new Uint8Array(width * height); fallback[nearest] = 255; claimed[nearest] = 1; extracted = boundsFromFullMask(fallback, width, height); } } if (!extracted) { const anchor = byId.get(ANCHORS[type][0])!; const x = clamp(Math.round(anchor.x), 0, width - 1); const y = clamp(Math.round(anchor.y), 0, height - 1); extracted = { bounds: { x, y, width: 1, height: 1 }, mask: { width: 1, height: 1, alpha: [255] } }; } built.set(type, { zoneId: type, semanticType: type, label: SEMANTIC_TAXONOMY[type].label, parentZoneId: PARENTS[type], anchorLandmarkIds: ANCHORS[type], bounds: extracted.bounds, mask: extracted.mask, geometry: { kind: candidate.kind, centerline: candidate.centerline, polygon: candidate.polygon }, optional: false, refinementMargin: Math.max(2, Math.round(Math.min(width, height) * .025)) }); }
  return BODY_TYPES.map((type) => built.get(type)!);
}

export function buildAdaptiveAnatomicalPartitionGuide(state: Pick<PartCutterState, "sourceCanvasSize" | "parts">, foreground: readonly number[], requestedProfile: AnatomicalPartitionGuide["profile"] = "humanoid", timestamp = new Date().toISOString()): AnatomicalPartitionGuide {
  const started = typeof performance !== "undefined" ? performance.now() : Date.now(); const { width, height } = state.sourceCanvasSize; const alpha = foreground.map((value) => value > 0 ? 255 : 0); const profile = analyzeSilhouette(alpha, width, height); const analysis = descriptorFor(alpha, profile, requestedProfile); const landmarks = inferLandmarks(alpha, profile, analysis.descriptor, analysis.neckY, requestedProfile, analysis.hiddenLegs, analysis.armorLikely); const zones = adaptiveZones(alpha, width, height, landmarks, analysis.descriptor);
  const inferredLandmarkIds = landmarks.filter((landmark) => landmark.visibility === "inferred").map((landmark) => landmark.landmarkId); const needsReviewLandmarkIds = landmarks.filter((landmark) => landmark.visibility === "needs-review").map((landmark) => landmark.landmarkId);
  return { guideVersion: 1, profile: requestedProfile, sourceCanvasSize: state.sourceCanvasSize, landmarks, zones, adaptiveMetadata: { initializationMethod: "alpha-silhouette-adaptive-v1", topology: requestedProfile, topologyNeedsReview: requestedProfile === "custom" && analysis.descriptor.archetype === "custom", proportionDescriptor: analysis.descriptor, foregroundPixelCount: profile.foregroundPixelCount, inferredLandmarkIds, needsReviewLandmarkIds, runtimeMs: elapsed(started) }, status: "seeded", createdAt: timestamp, updatedAt: timestamp };
}

const affectedZones: Readonly<Record<AnatomicalLandmarkId, readonly PartSemanticType[]>> = { root: [], pelvis: ["torso", "pelvis"], chest: ["torso"], neck: ["head", "torso"], head: ["head"], leftShoulder: ["torso", "leftUpperArm"], leftElbow: ["leftUpperArm", "leftForearm"], leftWrist: ["leftForearm", "leftHand"], rightShoulder: ["torso", "rightUpperArm"], rightElbow: ["rightUpperArm", "rightForearm"], rightWrist: ["rightForearm", "rightHand"], leftHip: ["pelvis", "leftThigh"], leftKnee: ["leftThigh", "leftLowerLeg"], leftAnkle: ["leftLowerLeg", "leftFoot"], rightHip: ["pelvis", "rightThigh"], rightKnee: ["rightThigh", "rightLowerLeg"], rightAnkle: ["rightLowerLeg", "rightFoot"], leftHock: ["leftLowerLeg", "leftFoot"], rightHock: ["rightLowerLeg", "rightFoot"] };
export function moveAdaptiveLandmark(guide: AnatomicalPartitionGuide, landmarkId: AnatomicalLandmarkId, point: Point, foreground: readonly number[], timestamp = new Date().toISOString()): AnatomicalPartitionGuide {
  if (!guide.adaptiveMetadata) throw new Error("Legacy guides must be explicitly regenerated before adaptive landmark editing"); const { width, height } = guide.sourceCanvasSize; const landmarks = guide.landmarks.map((landmark) => landmark.landmarkId === landmarkId ? { ...landmark, point: roundPoint(point, width, height), source: "manual" as const, visibility: "manual" as const, confidence: 1, method: "direct landmark drag" } : landmark); const rebuilt = adaptiveZones(foreground, width, height, landmarks, guide.adaptiveMetadata.proportionDescriptor); const affected = new Set(affectedZones[landmarkId]); const zones = guide.zones.map((zone) => affected.has(zone.semanticType) ? rebuilt.find((candidate) => candidate.semanticType === zone.semanticType) ?? zone : zone); return { ...guide, landmarks, zones, adaptiveMetadata: { ...guide.adaptiveMetadata, inferredLandmarkIds: guide.adaptiveMetadata.inferredLandmarkIds.filter((id) => id !== landmarkId), needsReviewLandmarkIds: guide.adaptiveMetadata.needsReviewLandmarkIds.filter((id) => id !== landmarkId) }, updatedAt: timestamp };
}
