import type { StudioToolName } from "../../src/agent-control/validation/toolSchemas";

const descriptions: Readonly<Partial<Record<StudioToolName, string>>> = {
  studio_get_status: "Inspect the live Rigging Studio session, selection, validation, connection, and optional recent activity.",
  project_create: "Create one new in-memory character authoring project.",
  project_open: "Open a validated Rigging Studio character project object; this is explicit import, not a filesystem read.",
  project_save: "Save the active project to the Studio browser-local draft.",
  project_export: "Export the active validated project as structured JSON content.",
  character_set_prompt: "Set the active character description prompt.",
  character_generate_image: "Generate, regenerate, or vary character source art with the configured Studio provider.",
  character_import_generation: "Ingest approved external PNG or JPEG artwork into managed Studio generation storage and the active project pipeline.",
  character_get_generation: "Inspect the active generation and suitability result.",
  character_accept_generation: "Explicitly accept the active generation for preparation.",
  character_run_suitability_check: "Evaluate whether the source art is suitable for modular rigging.",
  character_segment: "Propose modular character parts from the active source generation.",
  character_get_parts: "Inspect concise character-part summaries or explicitly request full part records.",
  character_update_part: "Change a constrained set of semantic part properties.",
  character_repair_occlusion: "Request one hidden-area reconstruction for review without automatically accepting it.",
  parts_get_status: "Inspect semantic Part Cutter state, coverage, proposals, and accepted parts.",
  parts_auto_cut: "Analyze the active source and create a reviewable structured full-character cut proposal without accepting it.",
  parts_prompt_cut: "Create or revise a semantic cut proposal from a natural-language instruction while preserving unaffected work.",
  parts_get_proposal: "Inspect the active or named structured cut proposal, with masks omitted unless explicitly requested.",
  parts_render_proposal: "Render a safe SVG overlay preview of a cut proposal without filesystem access.",
  parts_accept_proposal: "Explicitly accept selected proposed cuts as one semantic part operation.",
  parts_reject_proposal: "Explicitly reject a pending cut proposal without changing accepted parts.",
  parts_update_semantic_type: "Assign one canonical semantic type and its hierarchy, layer, and articulation defaults.",
  parts_merge: "Merge two or more accepted semantic parts while retaining source coordinates.",
  parts_split: "Split one accepted part horizontally or vertically into two editable parts.",
  parts_set_mask: "Replace one constrained part-local alpha mask. This does not expose arbitrary bitmap or file editing.",
  parts_set_pivot: "Set one part pivot in original source-canvas coordinates.",
  parts_set_z_order: "Set deterministic draw order and an optional front, body, or back layer group.",
  parts_mark_occluded: "Mark one part complete, likely incomplete, or unknown for repair review.",
  parts_reconstruct: "Request hidden-area reconstruction for one semantic part and keep it behind review.",
  parts_get_unassigned_regions: "Inspect accepted-mask coverage and possible unassigned regions.",
  parts_finalize: "Extract transparent assets, validate source scale, and build the existing RigDefinition.",
  rig_create_proposal: "Build and validate a rig proposal from accepted segmented parts.",
  rig_accept_proposal: "Explicitly accept the current validated rig proposal into the live editor.",
  rig_get_summary: "Inspect the active rig, hierarchy, slots, and optional full validated definition.",
  rig_move_bone: "Move one bone in rig-local authoring coordinates through the normal undo history.",
  rig_rotate_bone: "Set one bone setup rotation in degrees through the normal undo history.",
  rig_set_pivot: "Set one slot pivot through the normal undo history.",
  rig_set_parent: "Reparent one bone while preventing missing parents and hierarchy cycles.",
  rig_set_slot_attachment: "Set the base attachment on one visual slot.",
  rig_set_slot_z_index: "Set one slot draw-order value.",
  character_apply_skin: "Preview one existing rig skin without changing animation data.",
  character_set_equipment: "Assign an attachment to one stable equipment slot in the active skin.",
  animation_list: "List concise summaries of all live animations.",
  animation_create: "Create an empty validated animation in the normal animation history.",
  animation_generate: "Generate and validate an animation using rig-aware Studio proposal logic.",
  animation_revise: "Revise one animation with rig-aware Studio proposal logic.",
  animation_get_summary: "Inspect one animation summary or explicitly request its full validated definition.",
  animation_set_keyframe: "Insert or replace one validated bone-transform keyframe.",
  animation_delete_keyframe: "Explicitly delete one identified keyframe.",
  animation_play: "Select and play an animation in the live editor.",
  animation_pause: "Pause live editor animation playback.",
  animation_seek: "Deterministically seek the live editor to a time in seconds.",
  animation_delete: "Explicitly delete one animation when at least one other remains.",
  preview_render: "Render a deterministic diagnostic animation contact sheet in the browser Studio.",
  preview_get_last: "Inspect metadata and resource location for the latest preview.",
  validation_get: "Run shared rig and animation validation and return current issues.",
  project_run_smoke_test: "Run deterministic schema, pivot, equipment, occlusion, and joint checks.",
  transaction_begin: "Begin one lightweight compound rig edit transaction.",
  transaction_commit: "Commit the active compound edit as one normal undo step.",
  transaction_rollback: "Roll back all edits in the active compound transaction.",
  character_create_from_prompt: "Start the prompt-to-character workflow and stop at an explicit human review boundary.",
  diagnostics_export_report: "Export JSON and optional Markdown diagnostics only under the managed Studio diagnostics directory.",
  diagnostics_export_torture_test: "Export canonical or revisioned torture-test results under the managed Studio diagnostics directory.",
  image_provider_status: "Check provider-neutral image-production availability without exposing sensitive environment details.",
  image_provider_list_capabilities: "List trusted image workflow capabilities and honest workflow/model availability.",
  comfy_get_status: "Check the configured localhost ComfyUI endpoint, queue, and trusted capability readiness.",
  image_generate_candidates: "Run one trusted image-production workflow sequentially and stop with a reviewable proposal.",
  character_generate_with_comfy: "Build the normal modular-character prompt, generate ComfyUI candidates, run available suitability aids, and stop at review.",
  image_get_proposal: "Inspect a managed image proposal, progress, reviews, warnings, and approval boundary.",
  image_get_candidates: "List managed candidate summaries and image resource locations for one proposal.",
  image_render_candidate_sheet: "Render and retrieve a clean candidate contact sheet; this records visual inspection evidence.",
  image_get_candidate: "Retrieve one candidate image and record current-session visual inspection evidence.",
  image_review_proposal: "Record a structured agent recommendation or rejection without approving production ingress.",
  image_approve_candidate: "Explicitly approve an inspected candidate when the proposal approval policy permits agent approval.",
  image_reject_candidate: "Explicitly reject one proposal candidate while preserving its diagnostic asset.",
  image_regenerate_proposal: "Create one controlled child proposal, subject to the two-round generation limit.",
  image_set_approval_policy: "Set manual or agent-recommendation approval for new proposals in one project; manual is the default.",
  image_cancel_proposal: "Request cancellation of the currently executing ComfyUI job for one proposal.",
  image_analyze_candidate_suitability: "Run the existing provider-neutral rig-suitability analyzer on one managed proposal candidate.",
  image_prepare_repair_context: "Prepare the active project's managed source and selected-part mask for an installed trusted repair workflow.",
  segmentation_status: "Inspect truthful image-conditioned segmentation, refinement, and reconstruction readiness with exact missing dependencies.",
  character_ai_cut: "Run the trusted Grounding DINO plus SAM2 character cut and install a reviewable proposal without accepting parts.",
  part_refine_mask: "Refine one named part mask through the trusted image-conditioned workflow while preserving every unrelated mask.",
  part_reconstruct_hidden: "Create one localized hidden-area reconstruction proposal from an explicit reviewed occlusion mask.",
  part_get_reconstruction_proposal: "Inspect one reconstruction proposal, consistency metrics, rotation checks, and inspection/approval state.",
  part_render_reconstruction_preview: "Render Original, Visible Part, Reconstructed, and ±20° rotation views; this records visual inspection evidence.",
  part_approve_reconstruction: "Approve an inspected reconstruction proposal that passed the structural consistency gate.",
  part_reject_reconstruction: "Reject one reconstruction proposal and preserve the original visible fragment.",
  background_remove: "Request trusted background removal when the capability is installed; otherwise return the exact missing dependency.",
  alpha_cleanup: "Request targeted trusted alpha-edge cleanup when installed; otherwise return the exact missing dependency.",
};

export const toolDescription = (name: StudioToolName): string => descriptions[name] ?? `Rigging Studio operation: ${name}`;
export const READ_ONLY_TOOLS = new Set<StudioToolName>([
  "studio_get_status", "character_get_generation", "character_get_parts", "parts_get_status", "parts_get_proposal", "parts_render_proposal", "parts_get_unassigned_regions", "rig_get_summary", "animation_list",
  "animation_get_summary", "preview_get_last", "validation_get",
  "image_provider_status", "image_provider_list_capabilities", "comfy_get_status", "image_get_proposal", "image_get_candidates", "image_get_candidate",
  "image_analyze_candidate_suitability",
  "image_prepare_repair_context",
  "segmentation_status", "part_get_reconstruction_proposal",
]);
