import { validateCandidateReviewResult, type CandidateReviewJob, type CandidateReviewResult, type CutCandidate } from "./schema";

export type CandidateValidatorFinding = { readonly candidateId: string; readonly code: "EMPTY_MASK" | "INVALID_DIMENSIONS" | "OUT_OF_FOREGROUND" | "PROTECTED_OWNERSHIP" | "SOURCE_HASH_MISMATCH" | "SEMANTIC_MISMATCH" | "ANCHOR_MISS"; readonly detail: string };
export type ArbitrationIdentity = { readonly projectId: string; readonly sessionId: string; readonly revision: string; readonly sourceHash: string; readonly candidateSetHash: string };
export type ArbitrationDecision = { readonly status: "SELECTED" | "RECOMMENDATION" | "NEEDS_ALTERNATIVE" | "UNRESOLVED" | "STALE"; readonly selectedCandidateId: string | null; readonly confidence: number; readonly reason: string; readonly failureClass: "NO_VALID_CANDIDATE" | "VISION_CHOSE_WRONG_PART" | "VISION_CHOSE_CONTAMINATED" | "VISION_REJECTED_GOOD" | "GEOMETRY_OVERRULED_GOOD" | "VALIDATOR_FALSE_REJECTION" | "LOW_CONFIDENCE_UNRESOLVED" | "STALE_REVIEW" | "OTHER"; readonly deterministicFindings: readonly CandidateValidatorFinding[] };

export type ArbitrationPolicy = { readonly automaticSelectionConfidence: number; readonly recommendationConfidence: number; readonly minimumGeometryScore: number; readonly maximumGeometryScoreDeficit: number; readonly maximumRounds: number };
export const DEFAULT_ARBITRATION_POLICY: ArbitrationPolicy = { automaticSelectionConfidence: .85, recommendationConfidence: .65, minimumGeometryScore: .25, maximumGeometryScoreDeficit: .15, maximumRounds: 2 };
const critical = new Set(["WRONG_PART", "TORSO_CONTAMINATION", "OPPOSITE_LIMB_CONTAMINATION", "EQUIPMENT_CONTAMINATION", "JOINT_UNUSABLE"]);

export function validateCutCandidate(candidate: CutCandidate, job: CandidateReviewJob, sourceAlpha: readonly number[], protectedAlpha: readonly number[] | undefined): readonly CandidateValidatorFinding[] {
  const findings: CandidateValidatorFinding[] = []; const add = (code: CandidateValidatorFinding["code"], detail: string) => findings.push({ candidateId: candidate.candidateId, code, detail });
  if (candidate.width <= 0 || candidate.height <= 0 || candidate.alpha.length !== candidate.width * candidate.height || candidate.width * candidate.height !== sourceAlpha.length) add("INVALID_DIMENSIONS", "Candidate dimensions differ from the submitted source");
  if (!candidate.alpha.some((value) => value > 0)) add("EMPTY_MASK", "Candidate mask is empty");
  if (candidate.sourceHash !== job.sourceHash) add("SOURCE_HASH_MISMATCH", "Candidate source hash differs from the review job");
  if (candidate.semantic !== job.semantic) add("SEMANTIC_MISMATCH", "Candidate semantic differs from the review target");
  if (candidate.alpha.some((value, index) => value > 0 && !(sourceAlpha[index] > 0))) add("OUT_OF_FOREGROUND", "Candidate selects pixels outside source foreground");
  if (protectedAlpha && candidate.alpha.some((value, index) => value > 0 && protectedAlpha[index] > 0)) add("PROTECTED_OWNERSHIP", "Candidate intersects protected manual ownership");
  const radius = 2; const missesAnchor = candidate.inputLandmarks.some((anchor) => { for (let y = Math.floor(anchor.y - radius); y <= Math.ceil(anchor.y + radius); y += 1) for (let x = Math.floor(anchor.x - radius); x <= Math.ceil(anchor.x + radius); x += 1) if (x >= 0 && y >= 0 && x < candidate.width && y < candidate.height && candidate.alpha[y * candidate.width + x] > 0) return false; return true; });
  if (missesAnchor) add("ANCHOR_MISS", "Candidate misses an articulation anchor region"); return findings;
}

export function arbitrateCandidates(input: { readonly job: CandidateReviewJob; readonly candidates: readonly CutCandidate[]; readonly review: CandidateReviewResult; readonly sourceAlpha: readonly number[]; readonly protectedAlpha?: readonly number[]; readonly currentIdentity: ArbitrationIdentity; readonly policy?: Partial<ArbitrationPolicy> }): ArbitrationDecision {
  const { job } = input; const identity = input.currentIdentity;
  if (identity.projectId !== job.projectId || identity.sessionId !== job.sessionId || identity.revision !== job.revision || identity.sourceHash !== job.sourceHash || identity.candidateSetHash !== job.candidateSetHash) return { status: "STALE", selectedCandidateId: null, confidence: 0, reason: "Project, session, revision, source, or candidate set changed before review completion", failureClass: "STALE_REVIEW", deterministicFindings: [] };
  const review = validateCandidateReviewResult(input.review, job); const findings = input.candidates.flatMap((candidate) => validateCutCandidate(candidate, job, input.sourceAlpha, input.protectedAlpha)); const invalid = new Set(findings.map((finding) => finding.candidateId)); const valid = input.candidates.filter((candidate) => !invalid.has(candidate.candidateId));
  if (!valid.length) return { status: job.round < 2 ? "NEEDS_ALTERNATIVE" : "UNRESOLVED", selectedCandidateId: null, confidence: review.confidence, reason: "Every candidate failed deterministic validation", failureClass: "NO_VALID_CANDIDATE", deterministicFindings: findings };
  if (review.decision !== "SELECT") return { status: job.round < 2 ? "NEEDS_ALTERNATIVE" : "UNRESOLVED", selectedCandidateId: null, confidence: review.confidence, reason: review.decision === "NONE_OF_THE_ABOVE" ? "Reviewer rejected every candidate" : "Reviewer requested an alternative set", failureClass: valid.length ? "VISION_REJECTED_GOOD" : "NO_VALID_CANDIDATE", deterministicFindings: findings };
  const assessments = new Map(review.assessments.map((assessment) => [assessment.candidateId, assessment])); const rankedSurvivors = review.rankedCandidateIds.map((candidateId) => valid.find((candidate) => candidate.candidateId === candidateId)).filter((candidate): candidate is CutCandidate => Boolean(candidate)).filter((candidate) => { const assessment = assessments.get(candidate.candidateId); return assessment?.articulationUsable && !assessment.reasonCodes.some((reason) => critical.has(reason)); });
  const chosen = rankedSurvivors[0]; if (!chosen || review.acceptedCandidateId !== chosen.candidateId) return { status: "UNRESOLVED", selectedCandidateId: null, confidence: review.confidence, reason: "Review selection failed deterministic or contamination filtering", failureClass: "VISION_CHOSE_CONTAMINATED", deterministicFindings: findings };
  const policy = { ...DEFAULT_ARBITRATION_POLICY, ...input.policy }; if (chosen.geometryScore < policy.minimumGeometryScore) return { status: "UNRESOLVED", selectedCandidateId: null, confidence: review.confidence, reason: "Vision choice lacks minimum geometric plausibility", failureClass: "GEOMETRY_OVERRULED_GOOD", deterministicFindings: findings };
  const geometryTop = [...valid].sort((left, right) => right.geometryScore - left.geometryScore || left.candidateId.localeCompare(right.candidateId))[0];
  if (geometryTop.geometryScore - chosen.geometryScore > policy.maximumGeometryScoreDeficit) return { status: "UNRESOLVED", selectedCandidateId: null, confidence: review.confidence, reason: "Vision choice falls outside the registered relative geometry tolerance", failureClass: "GEOMETRY_OVERRULED_GOOD", deterministicFindings: findings };
  if (review.confidence >= policy.automaticSelectionConfidence) return { status: "SELECTED", selectedCandidateId: chosen.candidateId, confidence: review.confidence, reason: "High-confidence reviewer choice survived deterministic and contamination vetoes", failureClass: "OTHER", deterministicFindings: findings };
  if (review.confidence >= policy.recommendationConfidence && geometryTop.candidateId === chosen.candidateId) return { status: "RECOMMENDATION", selectedCandidateId: chosen.candidateId, confidence: review.confidence, reason: "Reviewer and geometry agree, but confidence requires review", failureClass: "LOW_CONFIDENCE_UNRESOLVED", deterministicFindings: findings };
  return { status: "UNRESOLVED", selectedCandidateId: null, confidence: review.confidence, reason: "Confidence is below automatic-selection policy or geometry disagrees", failureClass: "LOW_CONFIDENCE_UNRESOLVED", deterministicFindings: findings };
}
