import type { Point, Rect } from "../character-generation/segmentation/segmentationSchema";
import type { AnatomicalPartitionGuide, PartSemanticType } from "../part-cutter";
import { sha256 } from "./schema";

export const DETERMINISTIC_CANDIDATE_FAMILIES = ["oriented-envelope", "anchor-corridor", "locally-widened-corridor", "joint-centered", "foreground-geodesic"] as const;
export type DeterministicCandidateFamily = (typeof DETERMINISTIC_CANDIDATE_FAMILIES)[number];
export type CandidateSideAssignment = "CHARACTER_LEFT" | "CHARACTER_RIGHT" | "MIDLINE" | "AMBIGUOUS";
export type DeterministicCandidateFeatureVector = {
  readonly foregroundPrecisionProxy: number; readonly envelopeCoverage: number; readonly anchorPathDistance: number; readonly jointAnchorContainment: number;
  readonly centroidDistance: number; readonly sideConsistency: number; readonly componentCount: number; readonly componentCompactness: number; readonly semanticSizeRatio: number;
  readonly neighboringEnvelopeIntrusion: number; readonly articulationRadius: number; readonly boneAxisAlignment: number; readonly endpointCoverage: number; readonly silhouetteContinuity: number;
};
export type DeterministicCandidate = {
  readonly candidateId: string; readonly semantic: PartSemanticType; readonly generator: DeterministicCandidateFamily; readonly sourceHash: string; readonly landmarkRevision: string;
  readonly topologySource: "adaptive" | "canonical";
  readonly anchorIds: readonly string[]; readonly geometryParameters: Readonly<Record<string, number>>; readonly candidateHash: string; readonly pixelCount: number; readonly componentCount: number;
  readonly sideAssignment: CandidateSideAssignment; readonly width: number; readonly height: number; readonly alpha: readonly number[]; readonly features: DeterministicCandidateFeatureVector;
  readonly normalizedFeatures: DeterministicCandidateFeatureVector; readonly weights: DeterministicCandidateFeatureVector; readonly score: number; readonly rejectionReasons: readonly string[];
};
export type DeterministicSelection = {
  readonly decision: "SELECT" | "NONE_VALID"; readonly selectedCandidateId: string | null; readonly ranking: readonly string[]; readonly candidates: readonly DeterministicCandidate[];
  readonly candidateSetHash: string; readonly generationMs: number; readonly rankingMs: number; readonly totalMs: number; readonly identity: { readonly projectId: string; readonly sessionId: string; readonly revision: string; readonly sourceHash: string; readonly candidateSetHash: string };
};
export type DeterministicSelectionInput = {
  readonly projectId: string; readonly sessionId: string; readonly revision: string; readonly sourceHash: string; readonly width: number; readonly height: number;
  readonly sourceAlpha: readonly number[]; readonly semantic: PartSemanticType; readonly guide: AnatomicalPartitionGuide; readonly characterLeftScreenSide?: "left" | "right";
  readonly fallbackGuide?: AnatomicalPartitionGuide;
  readonly protectedAlpha?: readonly number[]; readonly createdAt?: string;
};

const clamp = (value: number, min = 0, max = 1): number => Math.min(max, Math.max(min, value));
const distance = (a: Point, b: Point): number => Math.hypot(a.x - b.x, a.y - b.y);
const distanceToSegment = (point: Point, start: Point, end: Point): number => { const dx = end.x - start.x; const dy = end.y - start.y; const squared = dx * dx + dy * dy; if (!squared) return distance(point, start); const t = clamp(((point.x - start.x) * dx + (point.y - start.y) * dy) / squared); return distance(point, { x: start.x + dx * t, y: start.y + dy * t }); };
const distanceToPath = (point: Point, anchors: readonly Point[]): number => anchors.length === 1 ? distance(point, anchors[0]) : Math.min(...anchors.slice(1).map((anchor, index) => distanceToSegment(point, anchors[index], anchor)));
const pixelCount = (alpha: readonly number[]): number => alpha.reduce((count, value) => count + (value > 0 ? 1 : 0), 0);
const inRect = (x: number, y: number, rect: Rect): boolean => x >= rect.x && y >= rect.y && x < rect.x + rect.width && y < rect.y + rect.height;
const expand = (rect: Rect, margin: number, width: number, height: number): Rect => { const x = clamp(Math.floor(rect.x - margin), 0, width - 1); const y = clamp(Math.floor(rect.y - margin), 0, height - 1); const right = clamp(Math.ceil(rect.x + rect.width + margin), x + 1, width); const bottom = clamp(Math.ceil(rect.y + rect.height + margin), y + 1, height); return { x, y, width: right - x, height: bottom - y }; };
const centroid = (alpha: readonly number[], width: number): Point | null => { let x = 0; let y = 0; let count = 0; alpha.forEach((value, index) => { if (!value) return; x += index % width; y += Math.floor(index / width); count += 1; }); return count ? { x: x / count, y: y / count } : null; };
const boundsOf = (alpha: readonly number[], width: number, height: number): Rect | null => { let minX = width; let minY = height; let maxX = -1; let maxY = -1; alpha.forEach((value, index) => { if (!value) return; const x = index % width; const y = Math.floor(index / width); minX = Math.min(minX, x); minY = Math.min(minY, y); maxX = Math.max(maxX, x); maxY = Math.max(maxY, y); }); return maxX < 0 ? null : { x: minX, y: minY, width: maxX - minX + 1, height: maxY - minY + 1 }; };
const components = (alpha: readonly number[], width: number): readonly number[][] => { const seen = new Uint8Array(alpha.length); const result: number[][] = []; for (let start = 0; start < alpha.length; start += 1) { if (!alpha[start] || seen[start]) continue; const queue = [start]; const component: number[] = []; seen[start] = 1; for (let cursor = 0; cursor < queue.length; cursor += 1) { const index = queue[cursor]; component.push(index); const x = index % width; for (const next of [index - 1, index + 1, index - width, index + width]) { if (next < 0 || next >= alpha.length || seen[next] || !alpha[next] || Math.abs(next % width - x) > 1) continue; seen[next] = 1; queue.push(next); } } result.push(component); } return result; };
const fullMask = (input: DeterministicSelectionInput, predicate: (x: number, y: number) => boolean): number[] => input.sourceAlpha.map((value, index) => { if (!value || input.protectedAlpha?.[index]) return 0; const x = index % input.width; const y = Math.floor(index / input.width); return predicate(x, y) ? 255 : 0; });
const maskHash = (alpha: readonly number[]): string => sha256(Uint8Array.from(alpha, (value) => value ? 255 : 0));
const stableValue = (value: unknown): unknown => Array.isArray(value) ? value.map(stableValue) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).sort(([left], [right]) => left.localeCompare(right)).map(([key, item]) => [key, stableValue(item)])) : value;
const stableHash = (value: unknown): string => sha256(JSON.stringify(stableValue(value)));

const anchorSpec: Readonly<Partial<Record<PartSemanticType, readonly string[]>>> = {
  head: ["neck", "head"], torso: ["neck", "chest", "pelvis"], pelvis: ["leftHip", "pelvis", "rightHip"],
  leftUpperArm: ["leftShoulder", "leftElbow"], leftForearm: ["leftElbow", "leftWrist"], leftHand: ["leftElbow", "leftWrist"],
  rightUpperArm: ["rightShoulder", "rightElbow"], rightForearm: ["rightElbow", "rightWrist"], rightHand: ["rightElbow", "rightWrist"],
  leftThigh: ["leftHip", "leftKnee"], leftLowerLeg: ["leftKnee", "leftAnkle"], leftFoot: ["leftKnee", "leftAnkle"],
  rightThigh: ["rightHip", "rightKnee"], rightLowerLeg: ["rightKnee", "rightAnkle"], rightFoot: ["rightKnee", "rightAnkle"],
};
const sided = (semantic: PartSemanticType): "left" | "right" | null => semantic.startsWith("left") ? "left" : semantic.startsWith("right") ? "right" : null;
const swapSide = (value: string): string => value.startsWith("left") ? value.replace(/^left/, "right") : value.startsWith("right") ? value.replace(/^right/, "left") : value;
const guideSemantic = (semantic: PartSemanticType, characterLeftScreenSide: "left" | "right"): PartSemanticType => characterLeftScreenSide === "right" && sided(semantic) ? swapSide(semantic) as PartSemanticType : semantic;
const guideAnchorId = (anchorId: string, characterLeftScreenSide: "left" | "right"): string => characterLeftScreenSide === "right" ? swapSide(anchorId) : anchorId;
const expectedSide = (semantic: PartSemanticType): CandidateSideAssignment => semantic.startsWith("left") ? "CHARACTER_LEFT" : semantic.startsWith("right") ? "CHARACTER_RIGHT" : "MIDLINE";
const geometryTerminal = (semantic: PartSemanticType): boolean => semantic === "head" || /Hand|Foot$/.test(semantic);

function resolvedGeometry(input: DeterministicSelectionInput, guide: AnatomicalPartitionGuide): { zone: Rect; anchors: readonly Point[]; anchorIds: readonly string[]; neighboring: readonly Rect[]; terminal: boolean } {
  const leftSide = input.characterLeftScreenSide ?? "right"; const mapped = guideSemantic(input.semantic, leftSide); const zone = guide.zones.find((candidate) => candidate.semanticType === mapped)?.bounds;
  if (!zone) throw new Error(`Guide does not contain ${mapped}`); const ids = (anchorSpec[input.semantic] ?? guide.zones.find((candidate) => candidate.semanticType === mapped)?.anchorLandmarkIds ?? []).map((id) => guideAnchorId(id, leftSide));
  const anchors = ids.map((id) => guide.landmarks.find((landmark) => landmark.landmarkId === id)?.point).filter((point): point is Point => Boolean(point)); if (!anchors.length) throw new Error(`Guide has no articulation anchors for ${input.semantic}`);
  const targetGroup = sided(mapped); const neighboring = guide.zones.filter((candidate) => candidate.semanticType !== mapped && (candidate.semanticType === "torso" || candidate.semanticType === "pelvis" || sided(candidate.semanticType) !== targetGroup)).map((candidate) => candidate.bounds);
  const adjustedZone = input.semantic === "head" ? { ...zone, height: Math.min(input.height - zone.y, zone.height + input.height * .13) } : input.semantic === "torso" ? (() => { const chest = anchors[1] ?? anchors[0]; const pelvis = anchors.at(-1)!; const y = Math.max(zone.y, chest.y - input.height * .02); const bottom = Math.min(input.height, Math.max(zone.y + zone.height, pelvis.y + zone.height * .48)); return { x: zone.x, y, width: zone.width, height: bottom - y }; })() : zone;
  return { zone: adjustedZone, anchors, anchorIds: ids, neighboring, terminal: /Hand|Foot$/.test(input.semantic) };
}

function extendedPath(anchors: readonly Point[], terminal: boolean, semantic: PartSemanticType, scale: number): readonly Point[] {
  if (!terminal || anchors.length < 2) return anchors; const proximal = anchors[anchors.length - 2]; const distal = anchors[anchors.length - 1]; const dx = distal.x - proximal.x; const dy = distal.y - proximal.y; const length = Math.max(1, Math.hypot(dx, dy)); const foot = /Foot$/.test(semantic); const extension = foot ? .35 : .28; const downBias = foot ? Math.max(1, scale * .25) : scale * .08; return [...anchors, { x: distal.x + dx / length * scale * extension, y: distal.y + dy / length * scale * extension + downBias }];
}

const localThickness = (input: DeterministicSelectionInput, anchors: readonly Point[], fallback: number): number => {
  if (anchors.length < 2) return fallback; const start = anchors[0]; const end = anchors[anchors.length - 1]; const dx = end.x - start.x; const dy = end.y - start.y; const length = Math.max(1, Math.hypot(dx, dy)); const nx = -dy / length; const ny = dx / length; const spans: number[] = [];
  for (const t of [.25, .5, .75]) { const point = { x: start.x + dx * t, y: start.y + dy * t }; let span = 1; for (const direction of [-1, 1]) for (let step = 1; step <= fallback * 2; step += 1) { const x = Math.round(point.x + nx * step * direction); const y = Math.round(point.y + ny * step * direction); if (x < 0 || y < 0 || x >= input.width || y >= input.height || !input.sourceAlpha[y * input.width + x]) break; span += 1; } spans.push(span / 2); }
  return clamp(spans.reduce((sum, value) => sum + value, 0) / Math.max(1, spans.length), Math.max(1.5, fallback * .55), fallback * 1.25);
};

const sideAssignment = (alpha: readonly number[], width: number, semantic: PartSemanticType, characterLeftScreenSide: "left" | "right"): CandidateSideAssignment => { const center = centroid(alpha, width); if (!center || !sided(semantic)) return sided(semantic) ? "AMBIGUOUS" : "MIDLINE"; const expectedScreenRight = (semantic.startsWith("left") && characterLeftScreenSide === "right") || (semantic.startsWith("right") && characterLeftScreenSide === "left"); if (Math.abs(center.x - width / 2) <= width * .05) return "AMBIGUOUS"; const screenRight = center.x > width / 2; const characterSide = screenRight === (characterLeftScreenSide === "right") ? "CHARACTER_LEFT" : "CHARACTER_RIGHT"; return expectedScreenRight === screenRight ? characterSide : characterSide; };

const WEIGHTS: DeterministicCandidateFeatureVector = { foregroundPrecisionProxy: .02, envelopeCoverage: .08, anchorPathDistance: .16, jointAnchorContainment: .13, centroidDistance: .09, sideConsistency: .12, componentCount: .05, componentCompactness: .04, semanticSizeRatio: .09, neighboringEnvelopeIntrusion: .08, articulationRadius: .04, boneAxisAlignment: .04, endpointCoverage: .03, silhouetteContinuity: .03 };

const inset = (rect: Rect, margin: number, width: number, height: number): Rect => expand(rect, -Math.min(margin, (Math.min(rect.width, rect.height) - 1) / 2), width, height);
const inwardBand = (rect: Rect, centerX: number, fraction: number, width: number, height: number): Rect => { const bandWidth = Math.max(2, Math.ceil(rect.width * fraction)); return rect.x + rect.width / 2 < centerX ? { x: Math.max(0, rect.x + rect.width - bandWidth), y: Math.max(0, rect.y), width: Math.min(bandWidth, width - Math.max(0, rect.x + rect.width - bandWidth)), height: Math.min(rect.height, height - Math.max(0, rect.y)) } : { x: Math.max(0, rect.x), y: Math.max(0, rect.y), width: Math.min(bandWidth, width - Math.max(0, rect.x)), height: Math.min(rect.height, height - Math.max(0, rect.y)) }; };
const pathFor = (input: DeterministicSelectionInput, geometry: ReturnType<typeof resolvedGeometry>): readonly Point[] => {
  const short = Math.max(2, Math.min(geometry.zone.width, geometry.zone.height)); let path = extendedPath(geometry.anchors, geometry.terminal, input.semantic, short);
  if (input.semantic === "torso" && path.length >= 2) { path = path.slice(1); const end = path[path.length - 1]; path = [...path, { x: end.x, y: Math.min(input.height - 1, end.y + geometry.zone.height * .4) }]; }
  return path;
};
const shiftPathTowardCenter = (path: readonly Point[], amount: number, width: number): readonly Point[] => path.map((point) => ({ x: point.x + Math.sign(width / 2 - point.x) * amount, y: point.y }));

function features(alpha: readonly number[], input: DeterministicSelectionInput, geometry: ReturnType<typeof resolvedGeometry>, path: readonly Point[], expectedRadius: number): DeterministicCandidateFeatureVector {
  const count = pixelCount(alpha); const envelopePixels = alpha.reduce((sum, value, index) => sum + (value && inRect(index % input.width, Math.floor(index / input.width), geometry.zone) ? 1 : 0), 0); const center = centroid(alpha, input.width); const candidateBounds = boundsOf(alpha, input.width, input.height); const connected = components(alpha, input.width); const largest = connected.reduce((largest, component) => Math.max(largest, component.length), 0); const candidateSide = sideAssignment(alpha, input.width, input.semantic, input.characterLeftScreenSide ?? "right"); const desired = expectedSide(input.semantic);
  let pathDistance = 0; let samples = 0; alpha.forEach((value, index) => { if (!value) return; pathDistance += distanceToPath({ x: index % input.width, y: Math.floor(index / input.width) }, path); samples += 1; }); const meanPath = pathDistance / Math.max(1, samples); const anchorHits = geometry.anchors.filter((anchor) => { for (let y = Math.floor(anchor.y - 2); y <= Math.ceil(anchor.y + 2); y += 1) for (let x = Math.floor(anchor.x - 2); x <= Math.ceil(anchor.x + 2); x += 1) if (x >= 0 && y >= 0 && x < input.width && y < input.height && alpha[y * input.width + x]) return true; return false; }).length / geometry.anchors.length;
  const intrusion = alpha.reduce((sum, value, index) => { if (!value) return sum; const x = index % input.width; const y = Math.floor(index / input.width); return sum + (geometry.neighboring.filter((rect) => inRect(x, y, rect)).length >= 2 ? 1 : 0); }, 0) / Math.max(1, count); const zoneForeground = input.sourceAlpha.reduce((sum, value, index) => sum + (value && inRect(index % input.width, Math.floor(index / input.width), geometry.zone) ? 1 : 0), 0); const areaRatio = count / Math.max(1, zoneForeground); const compactness = candidateBounds ? count / (candidateBounds.width * candidateBounds.height) : 0; const radius = candidateBounds ? Math.min(candidateBounds.width, candidateBounds.height) / 2 : 0;
  const axis = path.length >= 2 ? { x: path[path.length - 1].x - path[0].x, y: path[path.length - 1].y - path[0].y } : { x: 0, y: 1 }; const boxAxis = candidateBounds ? (candidateBounds.height >= candidateBounds.width ? { x: 0, y: 1 } : { x: 1, y: 0 }) : { x: 0, y: 0 }; const axisLength = Math.max(1, Math.hypot(axis.x, axis.y)); const alignment = Math.abs((axis.x / axisLength) * boxAxis.x + (axis.y / axisLength) * boxAxis.y);
  const endpoint = path[path.length - 1]; let endpointHit = 0; for (let y = Math.floor(endpoint.y - expectedRadius); y <= Math.ceil(endpoint.y + expectedRadius); y += 1) for (let x = Math.floor(endpoint.x - expectedRadius); x <= Math.ceil(endpoint.x + expectedRadius); x += 1) if (x >= 0 && y >= 0 && x < input.width && y < input.height && alpha[y * input.width + x]) endpointHit = 1;
  return { foregroundPrecisionProxy: 1, envelopeCoverage: envelopePixels / Math.max(1, count), anchorPathDistance: clamp(1 - meanPath / Math.max(1, expectedRadius * 1.8)), jointAnchorContainment: anchorHits, centroidDistance: center ? clamp(1 - distanceToPath(center, path) / Math.max(1, expectedRadius * 2)) : 0, sideConsistency: desired === "MIDLINE" ? 1 : candidateSide === desired ? 1 : candidateSide === "AMBIGUOUS" ? .45 : 0, componentCount: 1 / Math.max(1, connected.length), componentCompactness: compactness, semanticSizeRatio: clamp(1 - Math.abs(areaRatio - .72) / .9), neighboringEnvelopeIntrusion: 1 - intrusion, articulationRadius: clamp(1 - Math.abs(radius - expectedRadius) / Math.max(1, expectedRadius * 1.5)), boneAxisAlignment: alignment, endpointCoverage: endpointHit, silhouetteContinuity: largest / Math.max(1, count) };
}

const preferredFamily = (semantic: PartSemanticType): DeterministicCandidateFamily => semantic === "head" ? "anchor-corridor" : semantic === "torso" || /Arm$|Forearm$|Hand$/.test(semantic) ? "foreground-geodesic" : "oriented-envelope";
const scoreFeatures = (value: DeterministicCandidateFeatureVector, family: DeterministicCandidateFamily, semantic: PartSemanticType): number => Object.keys(WEIGHTS).reduce((sum, key) => sum + value[key as keyof DeterministicCandidateFeatureVector] * WEIGHTS[key as keyof DeterministicCandidateFeatureVector], 0) + (family === preferredFamily(semantic) ? .2 : 0);
const semanticLocationPlausible = (alpha: readonly number[], input: DeterministicSelectionInput): boolean => { const center = centroid(alpha, input.width); if (!center) return false; const ratio = center.y / Math.max(1, input.height); if (input.semantic === "head") return ratio <= .45; if (input.semantic === "torso") return ratio >= .18 && ratio <= .75; if (/UpperArm$/.test(input.semantic)) return ratio >= .18 && ratio <= .7; if (/Forearm$/.test(input.semantic)) return ratio >= .28 && ratio <= .82; if (/Hand$/.test(input.semantic)) return ratio >= .4 && ratio <= .88; if (/Thigh$/.test(input.semantic)) return ratio >= .48 && ratio <= .92; if (/LowerLeg$/.test(input.semantic)) return ratio >= .62; if (/Foot$/.test(input.semantic)) return ratio >= .76; return true; };

export function selectDeterministicCandidate(input: DeterministicSelectionInput): DeterministicSelection {
  const started = typeof performance !== "undefined" ? performance.now() : Date.now(); if (input.sourceAlpha.length !== input.width * input.height) throw new Error("Source alpha dimensions are invalid"); if (input.protectedAlpha && input.protectedAlpha.length !== input.sourceAlpha.length) throw new Error("Protected ownership dimensions are invalid");
  const adaptive = resolvedGeometry(input, input.guide); const canonical = resolvedGeometry(input, input.fallbackGuide ?? input.guide); const adaptiveShort = Math.max(2, Math.min(adaptive.zone.width, adaptive.zone.height)); const canonicalShort = Math.max(2, Math.min(canonical.zone.width, canonical.zone.height)); const adaptiveRadius = clamp(localThickness(input, adaptive.anchors, adaptiveShort * .22), Math.max(1.5, adaptiveShort * .14), Math.max(2, adaptiveShort * .3)); const canonicalRadius = clamp(Math.max(localThickness(input, canonical.anchors, canonicalShort * .24), canonicalShort * .26), Math.max(1.75, canonicalShort * .2), Math.max(2.5, canonicalShort * .36)); const adaptivePath = pathFor(input, adaptive); const canonicalPath = pathFor(input, canonical); const canonicalExpanded = expand(canonical.zone, Math.max(1, canonicalShort * .12), input.width, input.height); const canonicalTerminal = canonicalPath[canonicalPath.length - 1]; const terminalRadius = input.semantic === "head" ? Math.max(4, canonical.zone.width * .43) : Math.max(canonicalRadius * 1.35, canonicalShort * .36); const inwardPath = shiftPathTowardCenter(canonicalPath, canonicalShort * .22, input.width); const innerZone = inset(canonical.zone, Math.max(1, canonicalShort * .09), input.width, input.height);
  const canonicalCenterX = canonical.zone.x + canonical.zone.width / 2; const inward = inwardBand(canonicalExpanded, input.width / 2, /Hand$/.test(input.semantic) ? .42 : .3, input.width, input.height); const forearmBandBase = inwardBand(canonical.zone, input.width / 2, .16, input.width, input.height); const forearmBand = { ...forearmBandBase, x: clamp(forearmBandBase.x + (forearmBandBase.x + forearmBandBase.width / 2 < input.width / 2 ? -1 : 1), 0, input.width - forearmBandBase.width) }; const distal = canonical.anchors[canonical.anchors.length - 1]; const proximal = canonical.anchors[0]; const upperInset = canonical.zone.width * .18; const upperArmRecovery = { x: canonical.zone.x + upperInset, y: canonical.zone.y + canonical.zone.height * .42, width: Math.max(1, canonical.zone.width - upperInset * 2), height: canonical.zone.height * .75 };
  const recoveryMask = input.semantic === "torso"
    ? fullMask(input, (x, y) => y >= canonical.zone.y + 1 && y <= distal.y + canonical.zone.height * .22 && Math.abs(x - canonicalCenterX) <= canonical.zone.width * .23)
    : /Hand$/.test(input.semantic)
      ? fullMask(input, (x, y) => inRect(x, y, inward) && y >= distal.y - Math.max(1, canonicalShort * .08))
      : /Forearm$/.test(input.semantic)
        ? fullMask(input, (x, y) => inRect(x, y, forearmBand) && y >= Math.min(proximal.y, distal.y) + Math.abs(distal.y - proximal.y) * .25 && y <= Math.max(proximal.y, distal.y) + canonicalShort * .25)
        : /UpperArm$/.test(input.semantic)
          ? fullMask(input, (x, y) => inRect(x, y, upperArmRecovery))
        : geometryTerminal(input.semantic)
          ? fullMask(input, (x, y) => inRect(x, y, canonicalExpanded) && distance({ x, y }, canonicalTerminal) <= terminalRadius * 1.12)
          : fullMask(input, (x, y) => inRect(x, y, canonicalExpanded) && distanceToPath({ x, y }, inwardPath) <= canonicalRadius * 1.02);
  const adaptiveEnvelope = !geometryTerminal(input.semantic) && input.semantic !== "torso" ? inset(adaptive.zone, 1, input.width, input.height) : adaptive.zone;
  const specifications: readonly { family: DeterministicCandidateFamily; topologySource: "adaptive" | "canonical"; geometry: typeof adaptive; path: readonly Point[]; expectedRadius: number; parameters: Readonly<Record<string, number>>; alpha: number[] }[] = [
    { family: "oriented-envelope", topologySource: "adaptive", geometry: adaptive, path: adaptivePath, expectedRadius: adaptiveRadius, parameters: { inset: adaptiveEnvelope === adaptive.zone ? 0 : 1 }, alpha: fullMask(input, (x, y) => inRect(x, y, adaptiveEnvelope)) },
    { family: "anchor-corridor", topologySource: "canonical", geometry: canonical, path: canonicalPath, expectedRadius: canonicalRadius, parameters: { envelopeInset: canonicalShort * .09 }, alpha: fullMask(input, (x, y) => inRect(x, y, innerZone)) },
    { family: "locally-widened-corridor", topologySource: "canonical", geometry: canonical, path: canonicalPath, expectedRadius: canonicalRadius, parameters: { radius: canonicalRadius * .72 }, alpha: fullMask(input, (x, y) => inRect(x, y, canonicalExpanded) && distanceToPath({ x, y }, canonicalPath) <= canonicalRadius * .72) },
    { family: "joint-centered", topologySource: "canonical", geometry: canonical, path: canonicalPath, expectedRadius: canonicalRadius, parameters: { radius: terminalRadius }, alpha: fullMask(input, (x, y) => inRect(x, y, canonicalExpanded) && (geometryTerminal(input.semantic) ? distance({ x, y }, canonicalTerminal) <= terminalRadius : distanceToPath({ x, y }, canonicalPath) <= canonicalRadius * 1.08)) },
    { family: "foreground-geodesic", topologySource: "canonical", geometry: canonical, path: input.semantic === "torso" ? canonicalPath : inwardPath, expectedRadius: canonicalRadius, parameters: { radius: canonicalRadius * 1.02, inwardShift: canonicalShort * .22 }, alpha: recoveryMask },
  ];
  const seen = new Set<string>(); const raw: Omit<DeterministicCandidate, "candidateId">[] = []; for (const specification of specifications) { const count = pixelCount(specification.alpha); if (!count) continue; const candidateHash = maskHash(specification.alpha); if (seen.has(candidateHash)) continue; seen.add(candidateHash); const featureVector = features(specification.alpha, input, specification.geometry, specification.path, specification.expectedRadius); const candidateSide = sideAssignment(specification.alpha, input.width, input.semantic, input.characterLeftScreenSide ?? "right"); const rejectionReasons: string[] = []; if (featureVector.jointAnchorContainment === 0) rejectionReasons.push("ZERO_JOINT_ANCHOR_RELATIONSHIP"); if (!semanticLocationPlausible(specification.alpha, input)) rejectionReasons.push("ANATOMICALLY_IMPOSSIBLE_LOCATION"); if (featureVector.sideConsistency === 0) rejectionReasons.push("WRONG_SIDE_HIGH_CERTAINTY"); if (featureVector.neighboringEnvelopeIntrusion < .12) rejectionReasons.push("CATASTROPHIC_MASS_INTRUSION"); if (featureVector.componentCount < .34) rejectionReasons.push("IMPOSSIBLE_DISCONNECTION"); if (count < 2) rejectionReasons.push("EMPTY_OR_TRIVIAL"); raw.push({ semantic: input.semantic, generator: specification.family, topologySource: specification.topologySource, sourceHash: input.sourceHash, landmarkRevision: input.revision, anchorIds: specification.geometry.anchorIds, geometryParameters: specification.parameters, candidateHash, pixelCount: count, componentCount: components(specification.alpha, input.width).length, sideAssignment: candidateSide, width: input.width, height: input.height, alpha: specification.alpha, features: featureVector, normalizedFeatures: featureVector, weights: WEIGHTS, score: scoreFeatures(featureVector, specification.family, input.semantic), rejectionReasons }); if (raw.length === 5) break; }
  const generatedAt = typeof performance !== "undefined" ? performance.now() : Date.now(); const candidates = raw.map((candidate, index) => ({ candidateId: String.fromCharCode(65 + index), ...candidate })); const survivors = candidates.filter((candidate) => !candidate.rejectionReasons.length).sort((left, right) => right.score - left.score || left.candidateHash.localeCompare(right.candidateHash)); const candidateSetHash = stableHash({ sourceHash: input.sourceHash, semantic: input.semantic, revision: input.revision, candidates: candidates.map((candidate) => ({ candidateHash: candidate.candidateHash, generator: candidate.generator, topologySource: candidate.topologySource, geometryParameters: candidate.geometryParameters })) }); const rankedAt = typeof performance !== "undefined" ? performance.now() : Date.now();
  const selected = survivors[0] && survivors[0].score >= .46 ? survivors[0] : null; return { decision: selected ? "SELECT" : "NONE_VALID", selectedCandidateId: selected?.candidateId ?? null, ranking: survivors.map((candidate) => candidate.candidateId), candidates, candidateSetHash, generationMs: generatedAt - started, rankingMs: rankedAt - generatedAt, totalMs: rankedAt - started, identity: { projectId: input.projectId, sessionId: input.sessionId, revision: input.revision, sourceHash: input.sourceHash, candidateSetHash } };
}

export function assertCurrentSelectionIdentity(selection: DeterministicSelection, current: DeterministicSelection["identity"]): void {
  if (selection.identity.projectId !== current.projectId || selection.identity.sessionId !== current.sessionId || selection.identity.revision !== current.revision || selection.identity.sourceHash !== current.sourceHash || selection.identity.candidateSetHash !== current.candidateSetHash) throw new Error("Stale deterministic candidate selection cannot mutate current ownership");
}
