import type { Rect, SegmentationMask } from "../character-generation/segmentation/segmentationSchema";
import { assignOwnershipSelection, decodeOwnership, ensureOwnershipPartition, type PartCutterState } from "../part-cutter";
import type { ArbitrationIdentity } from "./arbitration";
import { assertCurrentSelectionIdentity, type DeterministicCandidate, type DeterministicSelection } from "./deterministicGeometry";
import type { CandidateReviewJob, CutCandidate } from "./schema";

const crop = (candidate: Pick<CutCandidate, "width" | "height" | "alpha">): { readonly bounds: Rect; readonly mask: SegmentationMask } => { let minX = candidate.width; let minY = candidate.height; let maxX = -1; let maxY = -1; candidate.alpha.forEach((value, index) => { if (!value) return; const x = index % candidate.width; const y = Math.floor(index / candidate.width); minX = Math.min(minX, x); minY = Math.min(minY, y); maxX = Math.max(maxX, x); maxY = Math.max(maxY, y); }); if (maxX < 0) throw new Error("Cannot commit an empty candidate"); const width = maxX - minX + 1; const height = maxY - minY + 1; const alpha = Array.from({ length: width * height }, (_, index) => candidate.alpha[(minY + Math.floor(index / width)) * candidate.width + minX + index % width] ?? 0); return { bounds: { x: minX, y: minY, width, height }, mask: { width, height, alpha } }; };
const commitOwnership = (state: PartCutterState, targetPartId: string, semantic: string, candidate: Pick<DeterministicCandidate, "width" | "height" | "alpha">): { readonly state: PartCutterState; readonly changedPixels: number } => { const canonical = ensureOwnershipPartition(state, "ai"); const target = canonical.parts.find((part) => part.partId === targetPartId); if (!target || target.semanticType !== semantic) throw new Error("Target semantic region does not match the selected candidate"); const labels = decodeOwnership(canonical.ownership!); const manualIds = new Set(canonical.parts.filter((part) => part.provenance === "manual" && part.partId !== target.partId).map((part) => part.partId)); candidate.alpha.forEach((value, index) => { if (!value) return; const owner = labels[index]; const ownerId = owner > 0 ? canonical.ownership!.regionIds[owner - 1] : null; if (ownerId && manualIds.has(ownerId)) throw new Error(`Candidate would steal protected manual ownership from ${ownerId}`); }); const selection = crop(candidate); const committed = assignOwnershipSelection(canonical, target.partId, selection.bounds, selection.mask, { actor: "ai", action: "assign" }); return { state: committed.state, changedPixels: committed.changedPixels }; };

export function commitArbitratedCandidate(input: { readonly state: PartCutterState; readonly targetPartId: string; readonly candidate: CutCandidate; readonly job: CandidateReviewJob; readonly expectedIdentity: ArbitrationIdentity; readonly currentIdentity: ArbitrationIdentity }): { readonly state: PartCutterState; readonly changedPixels: number } {
  const { expectedIdentity: expected, currentIdentity: current, job, candidate } = input;
  if (Object.keys(expected).some((key) => expected[key as keyof ArbitrationIdentity] !== current[key as keyof ArbitrationIdentity])) throw new Error("Stale arbitration result cannot mutate current ownership");
  if (job.projectId !== current.projectId || job.sessionId !== current.sessionId || job.revision !== current.revision || job.sourceHash !== current.sourceHash || job.candidateSetHash !== current.candidateSetHash) throw new Error("Review identity no longer matches the current project");
  const manifest = job.candidates.find((item) => item.candidateId === candidate.candidateId); if (!manifest || manifest.candidateHash !== candidate.candidateHash) throw new Error("Candidate ID/hash is not part of the submitted candidate set");
  return commitOwnership(input.state, input.targetPartId, job.semantic, candidate);
}

export function commitDeterministicSelection(input: { readonly state: PartCutterState; readonly targetPartId: string; readonly selection: DeterministicSelection; readonly currentIdentity: DeterministicSelection["identity"] }): { readonly state: PartCutterState; readonly changedPixels: number } {
  assertCurrentSelectionIdentity(input.selection, input.currentIdentity); if (input.selection.decision !== "SELECT" || !input.selection.selectedCandidateId) throw new Error("NONE_VALID deterministic selection cannot mutate ownership"); const candidate = input.selection.candidates.find((item) => item.candidateId === input.selection.selectedCandidateId); if (!candidate || candidate.rejectionReasons.length) throw new Error("Selected deterministic candidate is not commit-eligible"); return commitOwnership(input.state, input.targetPartId, candidate.semantic, candidate);
}
